import mongoose from 'mongoose';
import path from 'path';
import { Category } from '../models/Category.js';
import { Product } from '../models/Product.js';
import { connectDB, disconnectDB } from '../config/db.js';

export const CATEGORIES_DATA = [
  {
    name: 'Fashion',
    slug: 'fashion',
    description: 'Ethnic wear, sarees, kurtas, denim, and handcrafted regional footwear.',
    icon: 'Shirt',
    image: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=600&q=80',
    displayOrder: 1,
  },
  {
    name: 'Mobiles',
    slug: 'mobiles',
    description: 'Latest 5G smartphones, affordable feature phones, and mobile accessories.',
    icon: 'Smartphone',
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=600&q=80',
    displayOrder: 2,
  },
  {
    name: 'Electronics',
    slug: 'electronics',
    description: 'Laptops, wireless audio, smartwatches, powerbanks, and computer gadgets.',
    icon: 'Laptop',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80',
    displayOrder: 3,
  },
  {
    name: 'Beauty',
    slug: 'beauty',
    description: 'Ayurvedic cosmetics, natural herbal haircare, makeup, and personal care.',
    icon: 'Sparkles',
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80',
    displayOrder: 4,
  },
  {
    name: 'Home',
    slug: 'home',
    description: 'Handcrafted pooja items, block-print bedsheets, terracotta matkas, and decor.',
    icon: 'Lamp',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=600&q=80',
    displayOrder: 5,
  },
  {
    name: 'Appliances',
    slug: 'appliances',
    description: 'Mixer grinders, desert air coolers, ceiling fans, smart TVs, and geysers.',
    icon: 'Tv',
    image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=600&q=80',
    displayOrder: 6,
  },
  {
    name: 'Medicine',
    slug: 'medicine',
    description: 'Essential medicines, Ayurvedic health tonics, first-aid kits, wellness care, and diagnostic monitors.',
    icon: 'Pill',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
    displayOrder: 7,
  },
];

export const PRODUCTS_DATA = [
  // ==========================================
  // FASHION (6 products)
  // ==========================================
  {
    categorySlug: 'fashion',
    title: 'Bhagalpuri Tussar Silk Handloom Saree',
    slug: 'bhagalpuri-tussar-silk-handloom-saree',
    brand: 'Virasat Weaves',
    price: 1899,
    mrp: 3499,
    discountPrice: 1899,
    unit: 'piece',
    weightKg: 0.6,
    stock: 45,
    originVillage: 'Nathnagar',
    originDistrict: 'Bhagalpur',
    originState: 'Bihar',
    isOrganic: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 124,
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Pure handloom Tussar silk saree with rich temple border and matching blouse piece.',
    description: 'Directly sourced from heritage weavers of Nathnagar, Bhagalpur. Hand-spun wild silk offering natural golden lustre, high breathability, and luxurious drape for auspicious celebrations.',
    tags: ['saree', 'silk', 'handloom', 'bhagalpur', 'ethnic'],
  },
  {
    categorySlug: 'fashion',
    title: 'Pure Cotton Chikankari Kurta for Men',
    slug: 'pure-cotton-chikankari-kurta-men',
    brand: 'Awadh Heritage',
    price: 799,
    mrp: 1599,
    discountPrice: 799,
    unit: 'piece',
    weightKg: 0.35,
    stock: 60,
    originVillage: 'Kakori',
    originDistrict: 'Lucknow',
    originState: 'Uttar Pradesh',
    isOrganic: true,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 89,
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Breathable Lucknowi Chikankari hand-embroidered long cotton kurta.',
    description: 'Fine modal cotton kurta featuring authentic shadow and murri embroidery stitches. Ideal for festive pooja ceremonies, summer gatherings, and traditional weddings.',
    tags: ['kurta', 'chikankari', 'men', 'cotton', 'ethnic'],
  },
  {
    categorySlug: 'fashion',
    title: 'Madhubani Hand-Painted Cotton Dupatta',
    slug: 'madhubani-hand-painted-cotton-dupatta',
    brand: 'Mithila Kala',
    price: 649,
    mrp: 1299,
    discountPrice: 649,
    unit: 'piece',
    weightKg: 0.25,
    stock: 35,
    originVillage: 'Ranti',
    originDistrict: 'Madhubani',
    originState: 'Bihar',
    isOrganic: true,
    isFeatured: false,
    rating: 4.9,
    reviewCount: 76,
    images: [
      'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Artisan hand-painted Mithila folk art motifs on fine Chanderi cotton fabric.',
    description: 'Crafted by award-winning women artisans in Ranti village. Uses natural organic mineral pigments depicting Matsya (fish) and lotus motifs symbolising prosperity.',
    tags: ['dupatta', 'madhubani', 'mithila', 'hand-painted'],
  },
  {
    categorySlug: 'fashion',
    title: 'Washed Indigo Denim Casual Shirt',
    slug: 'washed-indigo-denim-casual-shirt',
    brand: 'RuralTrend',
    price: 849,
    mrp: 1699,
    discountPrice: 849,
    unit: 'piece',
    weightKg: 0.45,
    stock: 80,
    originVillage: 'Bihta',
    originDistrict: 'Patna',
    originState: 'Bihar',
    isOrganic: false,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 52,
    images: [
      'https://images.unsplash.com/photo-1589310243389-96a5483213a8?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: '100% Cotton durable denim shirt with dual chest flap pockets.',
    description: 'Rugged all-weather casual shirt tailored from breathable 7.5 oz denim cloth with double-stitch reinforcement and brass press buttons.',
    tags: ['shirt', 'denim', 'casual', 'men'],
  },
  {
    categorySlug: 'fashion',
    title: 'Handcrafted Kolhapuri Pure Leather Chappals',
    slug: 'handcrafted-kolhapuri-leather-chappals',
    brand: 'Charam Craft',
    price: 599,
    mrp: 1199,
    discountPrice: 599,
    unit: 'pair',
    weightKg: 0.5,
    stock: 40,
    originVillage: 'Athani Road',
    originDistrict: 'Kolhapur',
    originState: 'Maharashtra',
    isOrganic: true,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 67,
    images: [
      'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Vegetable-tanned buffalo leather footwear with braided toe loop.',
    description: 'Traditional handcrafted ethnic chappals made using natural tree bark tanning. Offers orthopaedic arch support and gets softer with daily use.',
    tags: ['chappal', 'leather', 'footwear', 'kolhapuri'],
  },
  {
    categorySlug: 'fashion',
    title: 'Women Embroidered Anarkali Kurti & Palazzo Set',
    slug: 'women-embroidered-anarkali-kurti-palazzo-set',
    brand: 'Pehnawa Select',
    price: 1299,
    mrp: 2499,
    discountPrice: 1299,
    unit: 'set',
    weightKg: 0.7,
    stock: 50,
    originVillage: 'Hajipur Market',
    originDistrict: 'Vaishali',
    originState: 'Bihar',
    isOrganic: false,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 95,
    images: [
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Flared Rayon Anarkali kurti paired with matching palazzos and dupatta.',
    description: 'Elegant flared floral printed ethnic suit set with golden zari detailing on the yoke. Lightweight, sweat-resistant fabric designed for full-day festival celebrations.',
    tags: ['kurti', 'anarkali', 'women', 'palazzo', 'ethnic'],
  },

  // ==========================================
  // MOBILES (6 products)
  // ==========================================
  {
    categorySlug: 'mobiles',
    title: 'Redmi 13C 5G (Starlight Silver, 128GB Storage)',
    slug: 'redmi-13c-5g-starlight-silver-128gb',
    brand: 'Xiaomi',
    price: 9999,
    mrp: 13999,
    discountPrice: 9999,
    unit: 'piece',
    weightKg: 0.38,
    stock: 30,
    originVillage: 'Industrial Zone',
    originDistrict: 'Noida',
    originState: 'Uttar Pradesh',
    isOrganic: false,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 310,
    images: [
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Dimensity 6100+ 5G Processor, 50MP AI Dual Camera, 5000mAh Battery.',
    description: 'Fast dual 5G SIM smartphone with 6.74-inch 90Hz display protected by Corning Gorilla Glass. Comes with 18W fast charging and clean side fingerprint sensor.',
    tags: ['mobile', 'smartphone', '5g', 'redmi', 'xiaomi'],
  },
  {
    categorySlug: 'mobiles',
    title: 'Realme Narzo 70x 5G (Forest Green, 128GB)',
    slug: 'realme-narzo-70x-5g-forest-green-128gb',
    brand: 'Realme',
    price: 11499,
    mrp: 15999,
    discountPrice: 11499,
    unit: 'piece',
    weightKg: 0.4,
    stock: 25,
    originVillage: 'Electronic City',
    originDistrict: 'Greater Noida',
    originState: 'Uttar Pradesh',
    isOrganic: false,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 180,
    images: [
      'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: '45W SUPERVOOC Fast Charge, 120Hz Ultra Smooth Display, IP54 Water Resistance.',
    description: 'Equipped with MediaTek Dimensity 6100+ 6nm architecture, dual stereo speakers, Rainwater Smart Touch technology and 5000mAh all-day battery.',
    tags: ['mobile', 'smartphone', '5g', 'realme'],
  },
  {
    categorySlug: 'mobiles',
    title: 'Samsung Galaxy M15 5G (Celestial Blue, 128GB)',
    slug: 'samsung-galaxy-m15-5g-celestial-blue',
    brand: 'Samsung',
    price: 12999,
    mrp: 16999,
    discountPrice: 12999,
    unit: 'piece',
    weightKg: 0.42,
    stock: 20,
    originVillage: 'Tech Park',
    originDistrict: 'Noida',
    originState: 'Uttar Pradesh',
    isOrganic: false,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 420,
    images: [
      'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Super AMOLED 90Hz Display, 6000mAh Monster Battery, 50MP Triple Camera.',
    description: 'Features vibrant FHD+ Super AMOLED display with Vision Booster, 4 generations of OS updates, and Samsung Knox Vault security for financial transactions.',
    tags: ['mobile', 'smartphone', 'samsung', '5g', 'battery'],
  },
  {
    categorySlug: 'mobiles',
    title: 'POCO M6 Pro 5G (Power Black, 6GB RAM, 128GB)',
    slug: 'poco-m6-pro-5g-power-black-128gb',
    brand: 'POCO',
    price: 10499,
    mrp: 14999,
    discountPrice: 10499,
    unit: 'piece',
    weightKg: 0.39,
    stock: 35,
    originVillage: 'Sector 62',
    originDistrict: 'Noida',
    originState: 'Uttar Pradesh',
    isOrganic: false,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 165,
    images: [
      'https://images.unsplash.com/photo-1567581935884-3349723552ca?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Snapdragon 4 Gen 2 4nm 5G processor, premium glass back finish.',
    description: 'Offers sleek glass back design, IP53 splash protection, IR blaster remote for TV/fans, and a crisp 6.79-inch 90Hz adaptive display.',
    tags: ['mobile', 'poco', 'snapdragon', '5g'],
  },
  {
    categorySlug: 'mobiles',
    title: 'Itel Super Guru 4G Keypad Phone with UPI Support',
    slug: 'itel-super-guru-4g-keypad-phone-upi',
    brand: 'Itel',
    price: 1799,
    mrp: 2499,
    discountPrice: 1799,
    unit: 'piece',
    weightKg: 0.22,
    stock: 90,
    originVillage: 'Phase 2',
    originDistrict: 'Noida',
    originState: 'Uttar Pradesh',
    isOrganic: false,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 215,
    images: [
      'https://images.unsplash.com/photo-1525598912003-663126343e1f?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Dual 4G VoLTE feature phone with instant QR scan UPI payments & FM radio.',
    description: 'Built specifically for rural users and merchants. Supports direct scan-to-pay UPI payments via NPCI 123PAY, King Voice reader, and massive 1000mAh standby battery.',
    tags: ['mobile', 'keypad', 'upi', 'itel', 'feature-phone'],
  },
  {
    categorySlug: 'mobiles',
    title: 'OnePlus Nord CE4 Lite 5G (Mega Blue, 128GB)',
    slug: 'oneplus-nord-ce4-lite-5g-mega-blue',
    brand: 'OnePlus',
    price: 19999,
    mrp: 22999,
    discountPrice: 19999,
    unit: 'piece',
    weightKg: 0.42,
    stock: 18,
    originVillage: 'Industrial Area',
    originDistrict: 'Gurugram',
    originState: 'Haryana',
    isOrganic: false,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 380,
    images: [
      'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: '80W SUPERVOOC Fast Charge, Sony LYT-600 OIS 50MP Camera, 120Hz AMOLED.',
    description: 'Brilliant 2,100 nits peak brightness display, 5500mAh high capacity battery, 300% Ultra Volume Mode, and 5W reverse charging.',
    tags: ['mobile', 'oneplus', 'amoled', '5g', 'flagship'],
  },

  // ==========================================
  // ELECTRONICS (6 products)
  // ==========================================
  {
    categorySlug: 'electronics',
    title: 'boAt Rockerz 255 Pro+ Wireless Bluetooth Neckband',
    slug: 'boat-rockerz-255-pro-wireless-neckband',
    brand: 'boAt',
    price: 1199,
    mrp: 3990,
    discountPrice: 1199,
    unit: 'piece',
    weightKg: 0.15,
    stock: 120,
    originVillage: 'Sector 18',
    originDistrict: 'Gurugram',
    originState: 'Haryana',
    isOrganic: false,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 650,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: '40 hours total playtime, ASAP Charge (10 mins = 10 hrs), IPX7 sweatproof.',
    description: 'Signature boAt extra bass with 10mm dynamic drivers. Includes magnetic earbuds, dual pairing, Bluetooth v5.2, and type-C fast charging.',
    tags: ['electronics', 'earphones', 'bluetooth', 'neckband', 'boat'],
  },
  {
    categorySlug: 'electronics',
    title: 'Noise ColorFit Pulse 3 Smartwatch (1.96-inch HD Display)',
    slug: 'noise-colorfit-pulse-3-smartwatch',
    brand: 'Noise',
    price: 1499,
    mrp: 4999,
    discountPrice: 1499,
    unit: 'piece',
    weightKg: 0.18,
    stock: 75,
    originVillage: 'Udyog Vihar',
    originDistrict: 'Gurugram',
    originState: 'Haryana',
    isOrganic: false,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 420,
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Bluetooth calling, 100+ sports modes, SpO2 & 24/7 heart rate monitor.',
    description: 'Vibrant 1.96-inch TFT screen with 550 nits brightness, 7-day battery life, AI voice assistant support, and robust IP68 water resistance.',
    tags: ['electronics', 'smartwatch', 'fitness', 'noise'],
  },
  {
    categorySlug: 'electronics',
    title: 'Mi 20000mAh 18W Fast Charging Power Bank 3i',
    slug: 'mi-20000mah-fast-charging-power-bank-3i',
    brand: 'Xiaomi',
    price: 1999,
    mrp: 2999,
    discountPrice: 1999,
    unit: 'piece',
    weightKg: 0.45,
    stock: 55,
    originVillage: 'Phase 2',
    originDistrict: 'Noida',
    originState: 'Uttar Pradesh',
    isOrganic: false,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 380,
    images: [
      'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Triple output ports, dual input (Type-C & Micro USB), 12-layer circuit protection.',
    description: 'High capacity lithium polymer power bank capable of charging standard smartphones 4 to 5 times. Features smart power management for earbuds and smartwatches.',
    tags: ['electronics', 'powerbank', 'battery', 'charger', 'mi'],
  },
  {
    categorySlug: 'electronics',
    title: 'HP 15s Intel Core i3 12th Gen Thin & Light Laptop (8GB/512GB SSD)',
    slug: 'hp-15s-intel-core-i3-laptop-512gb',
    brand: 'HP',
    price: 35990,
    mrp: 47990,
    discountPrice: 35990,
    unit: 'piece',
    weightKg: 2.1,
    stock: 15,
    originVillage: 'Cyber Hub',
    originDistrict: 'Bengaluru',
    originState: 'Karnataka',
    isOrganic: false,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 190,
    images: [
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: '15.6-inch FHD Anti-Glare display, Windows 11 Home, MS Office, Fast Charge.',
    description: '12th Gen Intel Core i3-1215U processor with 6 cores and 8 threads. Includes 512GB PCIe NVMe SSD, HP True Vision 720p HD camera with dual array mics.',
    tags: ['electronics', 'laptop', 'hp', 'computer'],
  },
  {
    categorySlug: 'electronics',
    title: 'JBL Go 3 Ultra-Portable Waterproof Bluetooth Speaker',
    slug: 'jbl-go-3-waterproof-bluetooth-speaker',
    brand: 'JBL',
    price: 2999,
    mrp: 3999,
    discountPrice: 2999,
    unit: 'piece',
    weightKg: 0.3,
    stock: 45,
    originVillage: 'Infotech City',
    originDistrict: 'Pune',
    originState: 'Maharashtra',
    isOrganic: false,
    isFeatured: false,
    rating: 4.9,
    reviewCount: 290,
    images: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'JBL Pro Sound with punchy bass, IP67 waterproof & dustproof, 5 hours playtime.',
    description: 'Ultra-compact pocket speaker with rugged fabric loop. Plays uninterrupted music wirelessly through Bluetooth 5.1 in wet or dusty rural environments.',
    tags: ['electronics', 'speaker', 'bluetooth', 'jbl', 'audio'],
  },
  {
    categorySlug: 'electronics',
    title: 'SanDisk Ultra 128GB MicroSDXC Card (140MB/s Speed)',
    slug: 'sandisk-ultra-128gb-microsdxc-card',
    brand: 'SanDisk',
    price: 849,
    mrp: 1800,
    discountPrice: 849,
    unit: 'piece',
    weightKg: 0.05,
    stock: 150,
    originVillage: 'Electronic City',
    originDistrict: 'Bengaluru',
    originState: 'Karnataka',
    isOrganic: false,
    isFeatured: false,
    rating: 4.9,
    reviewCount: 520,
    images: [
      'https://images.unsplash.com/photo-1562975079-6a69399827a5?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Class 10, A1 App Performance rated high-speed storage memory card.',
    description: 'Ideal for Android smartphones, tablets, and surveillance cameras. Waterproof, temperature-proof, X-ray proof and shockproof with 10-year warranty.',
    tags: ['electronics', 'memory-card', 'sandisk', 'storage'],
  },

  // ==========================================
  // BEAUTY (6 products)
  // ==========================================
  {
    categorySlug: 'beauty',
    title: 'Mamaearth Ubtan Natural Face Wash (Turmeric & Saffron, 150ml)',
    slug: 'mamaearth-ubtan-natural-face-wash-150ml',
    brand: 'Mamaearth',
    price: 349,
    mrp: 449,
    discountPrice: 349,
    unit: 'bottle',
    weightKg: 0.2,
    stock: 80,
    originVillage: 'Dharuhera',
    originDistrict: 'Rewari',
    originState: 'Haryana',
    isOrganic: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 310,
    images: [
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Tan removal face wash with walnut beads, turmeric, and pure saffron.',
    description: 'Dermatologically tested formula free of sulphates, parabens, SLS, and mineral oils. Gently exfoliates dead skin cells to restore radiant natural village glow.',
    tags: ['beauty', 'face-wash', 'ubtan', 'skincare', 'organic'],
  },
  {
    categorySlug: 'beauty',
    title: 'Khadi Natural Ayurvedic Herbal Hair Oil (Amla & Brahmi, 210ml)',
    slug: 'khadi-natural-ayurvedic-hair-oil-amla-brahmi',
    brand: 'Khadi Natural',
    price: 220,
    mrp: 295,
    discountPrice: 220,
    unit: 'bottle',
    weightKg: 0.28,
    stock: 95,
    originVillage: 'Rampur Garden',
    originDistrict: 'Bareilly',
    originState: 'Uttar Pradesh',
    isOrganic: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 240,
    images: [
      'https://images.unsplash.com/photo-1608248597359-0026e4922116?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Pure herbal cold-pressed hair revitalizer preventing premature greying and dandruff.',
    description: 'Authentic Gramodyog formulation enriched with Indian gooseberry (amla), brahmi, neem, and sesame oil. Deeply nourishes the scalp roots.',
    tags: ['beauty', 'hair-oil', 'ayurvedic', 'khadi', 'haircare'],
  },
  {
    categorySlug: 'beauty',
    title: 'Maybelline New York Colossal Kajal (Deep Black, 24HR Waterproof)',
    slug: 'maybelline-colossal-kajal-deep-black',
    brand: 'Maybelline',
    price: 165,
    mrp: 199,
    discountPrice: 165,
    unit: 'piece',
    weightKg: 0.05,
    stock: 140,
    originVillage: 'Baddi Industrial Area',
    originDistrict: 'Solan',
    originState: 'Himachal Pradesh',
    isOrganic: false,
    isFeatured: false,
    rating: 4.8,
    reviewCount: 480,
    images: [
      'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Smudge-proof 24-hour eye pencil enriched with soothing Aloe Vera extract.',
    description: 'Intense black pigments delivering deep eye definition in a single glide. Ophthalmologist tested and safe for sensitive eyes and contact lens wearers.',
    tags: ['beauty', 'kajal', 'eyeliner', 'makeup'],
  },
  {
    categorySlug: 'beauty',
    title: 'Nivea Soft Light Moisturising Cream (200ml Jar)',
    slug: 'nivea-soft-light-moisturising-cream-200ml',
    brand: 'Nivea',
    price: 299,
    mrp: 399,
    discountPrice: 299,
    unit: 'jar',
    weightKg: 0.25,
    stock: 110,
    originVillage: 'Sanand Industrial Estate',
    originDistrict: 'Ahmedabad',
    originState: 'Gujarat',
    isOrganic: false,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 520,
    images: [
      'https://images.unsplash.com/photo-1556228722-d0b7410298a0?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Quick-absorbing non-greasy daily moisturizer with Vitamin E & Jojoba Oil.',
    description: 'Refreshing lightweight hydration suitable for face, hands, and body. Leaves skin feeling soft, smooth, and refreshed throughout winter and dry seasons.',
    tags: ['beauty', 'moisturizer', 'cream', 'skincare', 'nivea'],
  },
  {
    categorySlug: 'beauty',
    title: 'Biotique Bio Kelp Protein Anti-Hair Fall Shampoo (340ml)',
    slug: 'biotique-bio-kelp-anti-hair-fall-shampoo',
    brand: 'Biotique',
    price: 280,
    mrp: 360,
    discountPrice: 280,
    unit: 'bottle',
    weightKg: 0.4,
    stock: 70,
    originVillage: 'Kala Amb',
    originDistrict: 'Sirmaur',
    originState: 'Himachal Pradesh',
    isOrganic: true,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 165,
    images: [
      'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Ayurvedic therapeutic shampoo with pure kelp, bhringraj, and neem bark.',
    description: '100% botanical extract formulation invigorating scalp follicles and promoting healthy hair growth while retaining natural moisture.',
    tags: ['beauty', 'shampoo', 'biotique', 'haircare', 'ayurvedic'],
  },
  {
    categorySlug: 'beauty',
    title: 'SUGAR Matte As Hell Crayon Lipstick with Free Sharpener',
    slug: 'sugar-matte-as-hell-crayon-lipstick',
    brand: 'SUGAR Cosmetics',
    price: 699,
    mrp: 899,
    discountPrice: 699,
    unit: 'piece',
    weightKg: 0.08,
    stock: 65,
    originVillage: 'Andheri East',
    originDistrict: 'Mumbai',
    originState: 'Maharashtra',
    isOrganic: false,
    isFeatured: false,
    rating: 4.8,
    reviewCount: 190,
    images: [
      'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Ultra-matte velvety pigmented crayon lipstick with 12-hour stay.',
    description: 'Glides on smoothly for full coverage in a single stroke without drying lips. Includes a specially designed high-grade dual sharpener.',
    tags: ['beauty', 'lipstick', 'makeup', 'sugar'],
  },

  // ==========================================
  // HOME (6 products)
  // ==========================================
  {
    categorySlug: 'home',
    title: 'Handcrafted Brass Pooja Bell with Garuda Handle',
    slug: 'handcrafted-brass-pooja-bell-garuda',
    brand: 'Kashi Artisans',
    price: 450,
    mrp: 750,
    discountPrice: 450,
    unit: 'piece',
    weightKg: 0.4,
    stock: 80,
    originVillage: 'Thatheri Bazaar',
    originDistrict: 'Varanasi',
    originState: 'Uttar Pradesh',
    isOrganic: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 210,
    images: [
      'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Pure bell-metal brass ghanti cast by traditional temple coppersmiths.',
    description: 'Produces a long, clear resonating sound that purifies home mandir energy. Intricately carved Garuda crest on top of the solid brass handle.',
    tags: ['home', 'pooja', 'brass', 'mandir', 'handicraft'],
  },
  {
    categorySlug: 'home',
    title: 'Jaipuri Pure Cotton Double Bedsheet with 2 Pillow Covers',
    slug: 'jaipuri-cotton-double-bedsheet-pillow-covers',
    brand: 'Rajasthan Craft',
    price: 749,
    mrp: 1499,
    discountPrice: 749,
    unit: 'set',
    weightKg: 0.95,
    stock: 60,
    originVillage: 'Sanganer',
    originDistrict: 'Jaipur',
    originState: 'Rajasthan',
    isOrganic: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 175,
    images: [
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: '100% Cotton 180 TC king size bedsheet with traditional Sanganeri hand print.',
    description: 'Colourfast and shrink-resistant breathable bedsheet measuring 90x108 inches. Comes with two matching envelope-closure pillow covers.',
    tags: ['home', 'bedsheet', 'cotton', 'jaipuri', 'furnishing'],
  },
  {
    categorySlug: 'home',
    title: 'Terracotta Natural Cooling Clay Water Pot (8L with Brass Tap)',
    slug: 'terracotta-clay-water-pot-8l-brass-tap',
    brand: 'Mitti Heritage',
    price: 580,
    mrp: 950,
    discountPrice: 580,
    unit: 'piece',
    weightKg: 3.5,
    stock: 35,
    originVillage: 'Kumhar Toli',
    originDistrict: 'Gorakhpur',
    originState: 'Uttar Pradesh',
    isOrganic: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 140,
    images: [
      'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Natural alkaline clay matka handmade by village potters with brass dispenser tap.',
    description: 'Naturally chills drinking water without electricity while enriching it with essential minerals. Heavy-fired clay with smooth earthen lid.',
    tags: ['home', 'clay', 'terracotta', 'matka', 'pottery'],
  },
  {
    categorySlug: 'home',
    title: 'Warm LED Wooden Tripod Bedside Table Lamp',
    slug: 'warm-led-wooden-tripod-bedside-lamp',
    brand: 'HomeGlow',
    price: 899,
    mrp: 1799,
    discountPrice: 899,
    unit: 'piece',
    weightKg: 0.8,
    stock: 45,
    originVillage: 'Saharanpur Craft Hub',
    originDistrict: 'Saharanpur',
    originState: 'Uttar Pradesh',
    isOrganic: false,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 95,
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Modern rustic table lamp with solid pine wood tripod legs and flax fabric shade.',
    description: 'Emits a soft eye-friendly amber glow for bedroom reading and nightstand ambiance. Standard E27 socket compatible with all LED bulbs.',
    tags: ['home', 'lamp', 'lighting', 'decor', 'table-lamp'],
  },
  {
    categorySlug: 'home',
    title: 'Stainless Steel 5-Tier Kitchen Spice & Vegetable Rack',
    slug: 'stainless-steel-5-tier-kitchen-rack',
    brand: 'Ratan Kitchenware',
    price: 699,
    mrp: 1299,
    discountPrice: 699,
    unit: 'piece',
    weightKg: 1.8,
    stock: 50,
    originVillage: 'Wazirpur Industrial Area',
    originDistrict: 'Delhi',
    originState: 'Delhi',
    isOrganic: false,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 88,
    images: [
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Corrosion-proof heavy gauge steel organizer for kitchen utensils and spices.',
    description: 'Sturdy multi-level kitchen shelf with non-slip rubber footing. Keeps condiments, oil dispensers, and vegetable baskets organized.',
    tags: ['home', 'kitchen', 'rack', 'storage', 'steel'],
  },
  {
    categorySlug: 'home',
    title: 'Handwoven Natural Jute & Cotton Dhurrie (3x5 Feet)',
    slug: 'handwoven-natural-jute-cotton-dhurrie',
    brand: 'Gramin Shilp',
    price: 899,
    mrp: 1699,
    discountPrice: 899,
    unit: 'piece',
    weightKg: 2.2,
    stock: 40,
    originVillage: 'Sitapur Handloom Cluster',
    originDistrict: 'Sitapur',
    originState: 'Uttar Pradesh',
    isOrganic: true,
    isFeatured: false,
    rating: 4.8,
    reviewCount: 110,
    images: [
      'https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Eco-friendly braided golden jute floor mat with rustic fringe borders.',
    description: 'Durable handloom woven rug for living rooms, corridors, and verandahs. Naturally dust-resistant, reversible, and biodegradable.',
    tags: ['home', 'jute', 'rug', 'dhurrie', 'carpet'],
  },

  // ==========================================
  // APPLIANCES (6 products)
  // ==========================================
  {
    categorySlug: 'appliances',
    title: 'Bajaj Rex 500W Mixer Grinder with 3 Stainless Steel Jars',
    slug: 'bajaj-rex-500w-mixer-grinder-3-jars',
    brand: 'Bajaj',
    price: 2199,
    mrp: 3600,
    discountPrice: 2199,
    unit: 'piece',
    weightKg: 3.2,
    stock: 40,
    originVillage: 'Chakan Industrial Zone',
    originDistrict: 'Pune',
    originState: 'Maharashtra',
    isOrganic: false,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 340,
    images: [
      'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: '500 Watts copper motor, 3 multi-function jars (1.2L, 0.8L, 0.3L), 1-yr warranty.',
    description: 'Rust-free stainless steel jars with vacuum suction rubber feet for vibration-free chutney grinding, dry masala powdering, and batter mixing.',
    tags: ['appliances', 'mixer', 'grinder', 'bajaj', 'kitchen'],
  },
  {
    categorySlug: 'appliances',
    title: 'Crompton Ozone 75L Desert Air Cooler (Honeycomb Pads)',
    slug: 'crompton-ozone-75l-desert-air-cooler',
    brand: 'Crompton',
    price: 9499,
    mrp: 14500,
    discountPrice: 9499,
    unit: 'piece',
    weightKg: 14.5,
    stock: 20,
    originVillage: 'Baddi',
    originDistrict: 'Solan',
    originState: 'Himachal Pradesh',
    isOrganic: false,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 280,
    images: [
      'https://images.unsplash.com/photo-1618941716939-553df3c6c278?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Everlast pump, dense honeycomb cooling, 4-way air deflection, inverter ready.',
    description: 'Cools large rooms up to 500 sq. ft. efficiently during scorching north Indian summers. Consumes only 190 watts and runs on home inverters.',
    tags: ['appliances', 'cooler', 'crompton', 'summer'],
  },
  {
    categorySlug: 'appliances',
    title: 'Usha Armor 1200mm High Speed Ceiling Fan (Rich Brown)',
    slug: 'usha-armor-1200mm-ceiling-fan-brown',
    brand: 'Usha',
    price: 1649,
    mrp: 2490,
    discountPrice: 1649,
    unit: 'piece',
    weightKg: 4.0,
    stock: 65,
    originVillage: 'Faridabad Industrial Area',
    originDistrict: 'Faridabad',
    originState: 'Haryana',
    isOrganic: false,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 195,
    images: [
      'https://images.unsplash.com/photo-1595475207225-428b62bda831?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: '380 RPM high air delivery, 100% copper wire winding motor, low voltage operation.',
    description: 'Glossy powder-coated finish resistant to corrosion and dust. Specially engineered blade aerofoil design for high air throw even in low voltage conditions.',
    tags: ['appliances', 'fan', 'ceiling-fan', 'usha'],
  },
  {
    categorySlug: 'appliances',
    title: 'Prestige Iris 2000W Induction Cooktop with Indian Menu',
    slug: 'prestige-iris-2000w-induction-cooktop',
    brand: 'Prestige',
    price: 2499,
    mrp: 3995,
    discountPrice: 2499,
    unit: 'piece',
    weightKg: 2.3,
    stock: 35,
    originVillage: 'Hosur Plant',
    originDistrict: 'Krishnagiri',
    originState: 'Tamil Nadu',
    isOrganic: false,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 230,
    images: [
      'https://images.unsplash.com/photo-1584269600519-112d071b35e6?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: '2000W fast heating, automatic voltage regulator, 7 preset Indian cooking modes.',
    description: 'Cooks roti, dal, milk, curry and idli with precision power control. Energy efficient flat glass ceramic panel with flame-free child safety protection.',
    tags: ['appliances', 'induction', 'cooktop', 'prestige', 'kitchen'],
  },
  {
    categorySlug: 'appliances',
    title: 'Mi 32-inch Horizon Edition HD Ready Smart Android TV',
    slug: 'mi-32-inch-horizon-smart-android-tv',
    brand: 'Xiaomi',
    price: 12999,
    mrp: 19999,
    discountPrice: 12999,
    unit: 'piece',
    weightKg: 4.8,
    stock: 22,
    originVillage: 'Sri City',
    originDistrict: 'Tirupati',
    originState: 'Andhra Pradesh',
    isOrganic: false,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 410,
    images: [
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Bezel-less Horizon display, PatchWall 4 with IMDb, 20W DTS-HD stereo audio.',
    description: 'Vivid Picture Engine rendering 16 million colors, dual-band Wi-Fi, built-in Chromecast, Google Assistant, and Google Play Store with 5000+ TV apps.',
    tags: ['appliances', 'tv', 'smart-tv', 'xiaomi', 'entertainment'],
  },
  {
    categorySlug: 'appliances',
    title: 'Havells Instanio 3-Litre Instant Water Heater Geyser (3000W)',
    slug: 'havells-instanio-3-litre-instant-water-heater',
    brand: 'Havells',
    price: 3499,
    mrp: 5990,
    discountPrice: 3499,
    unit: 'piece',
    weightKg: 3.1,
    stock: 28,
    originVillage: 'Neemrana Industrial Zone',
    originDistrict: 'Alwar',
    originState: 'Rajasthan',
    isOrganic: false,
    isFeatured: false,
    rating: 4.8,
    reviewCount: 160,
    images: [
      'https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Rust-proof ABS body with color changing LED heat indicator & stainless steel tank.',
    description: 'Instant hot water in under 2 minutes. Features high density PUF insulation, multi-function safety valve, and pressure withstand up to 6.5 bar.',
    tags: ['appliances', 'geyser', 'water-heater', 'havells', 'bathroom'],
  },

  // ==========================================
  // MEDICINE & HEALTHCARE (6 products)
  // ==========================================
  {
    categorySlug: 'medicine',
    title: 'Dabur Chyawanprash 2X Immunity Booster (1 kg)',
    slug: 'dabur-chyawanprash-immunity-booster-1kg',
    brand: 'Dabur',
    price: 385,
    mrp: 450,
    discountPrice: 385,
    unit: 'jar',
    weightKg: 1.0,
    stock: 60,
    originVillage: 'Sahibabad Pharma Zone',
    originDistrict: 'Ghaziabad',
    originState: 'Uttar Pradesh',
    isOrganic: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 310,
    images: [
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Clinically tested Ayurvedic formulation with 40+ vital herbs & Amla for 2X immunity.',
    description: 'Time-tested Ayurvedic formulation enriched with wild Indian Gooseberry (Amla), Ashwagandha, and Pippali. Promotes respiratory vitality, stamina, and defense against common seasonal infections.',
    tags: ['medicine', 'chyawanprash', 'ayurveda', 'immunity', 'dabur', 'healthcare'],
  },
  {
    categorySlug: 'medicine',
    title: 'Omron HEM-7120 Fully Automatic Digital BP Monitor',
    slug: 'omron-hem-7120-digital-blood-pressure-monitor',
    brand: 'Omron',
    price: 1849,
    mrp: 2640,
    discountPrice: 1849,
    unit: 'piece',
    weightKg: 0.5,
    stock: 25,
    originVillage: 'Medical Devices Hub',
    originDistrict: 'Gurugram',
    originState: 'Haryana',
    isOrganic: false,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 198,
    images: [
      'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'One-touch Intellisense automatic upper-arm blood pressure monitor with hypertension indicator.',
    description: 'Accurate and easy-to-use digital monitor featuring Intellisense technology for personalized inflation. Displays systolic, diastolic blood pressure, and pulse rate with irregular heartbeat detection.',
    tags: ['medicine', 'bp-monitor', 'omron', 'medical-device', 'healthcare'],
  },
  {
    categorySlug: 'medicine',
    title: 'Himalaya Liv.52 Herbal Liver Care Tablets (100 Tabs)',
    slug: 'himalaya-liv52-herbal-liver-care-100-tablets',
    brand: 'Himalaya Wellness',
    price: 165,
    mrp: 180,
    discountPrice: 165,
    unit: 'bottle',
    weightKg: 0.15,
    stock: 80,
    originVillage: 'Makali Wellness Park',
    originDistrict: 'Bengaluru',
    originState: 'Karnataka',
    isOrganic: true,
    isFeatured: false,
    rating: 4.8,
    reviewCount: 245,
    images: [
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Natural herbal hepatoprotective supplement supporting healthy liver function and metabolism.',
    description: 'Trusted herbal formulation with Caper Bush (Himsra) and Wild Chicory (Kasani). Promotes appetite, aids digestion, and protects hepatic parenchyma against toxins.',
    tags: ['medicine', 'liv52', 'himalaya', 'ayurveda', 'liver-care', 'tablets'],
  },
  {
    categorySlug: 'medicine',
    title: 'Dr. Morepen PO-09 Fingertip Pulse Oximeter with OLED Display',
    slug: 'dr-morepen-po-09-fingertip-pulse-oximeter',
    brand: 'Dr. Morepen',
    price: 749,
    mrp: 1499,
    discountPrice: 749,
    unit: 'piece',
    weightKg: 0.1,
    stock: 35,
    originVillage: 'Parwanoo Industrial Area',
    originDistrict: 'Solan',
    originState: 'Himachal Pradesh',
    isOrganic: false,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 142,
    images: [
      'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Accurate SpO2 oxygen saturation level and pulse rate monitor with multi-directional display.',
    description: 'Compact fingertip diagnostic tool for fast and painless measurement of blood oxygen saturation (SpO2) and pulse rate. Auto power-off feature and low battery indication.',
    tags: ['medicine', 'oximeter', 'dr-morepen', 'spo2', 'medical-device'],
  },
  {
    categorySlug: 'medicine',
    title: 'Savlon Antiseptic Liquid (1 L) + Emergency First-Aid Kit',
    slug: 'savlon-antiseptic-liquid-1l-first-aid-kit',
    brand: 'Savlon',
    price: 295,
    mrp: 350,
    discountPrice: 295,
    unit: 'pack',
    weightKg: 1.2,
    stock: 50,
    originVillage: 'Haridwar Industrial Estate',
    originDistrict: 'Haridwar',
    originState: 'Uttarakhand',
    isOrganic: false,
    isFeatured: false,
    rating: 4.9,
    reviewCount: 188,
    images: [
      'https://images.unsplash.com/photo-1603398938378-e54eab446dde?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Effective germ protection antiseptic liquid with bandages, sterile gauze, and medical cotton.',
    description: 'Hospital-grade antiseptic cleanser with Cetrimide and Chlorhexidine Gluconate for wound wash, cuts, burns, and home hygiene. Includes compact first-aid kit pouch.',
    tags: ['medicine', 'antiseptic', 'savlon', 'first-aid', 'hygiene', 'wound-care'],
  },
  {
    categorySlug: 'medicine',
    title: 'Zandu Balm Ultra Power Ayurvedic Pain Relief (25 ml x 2 Pack)',
    slug: 'zandu-balm-ultra-power-pain-relief-pack-of-2',
    brand: 'Zandu',
    price: 150,
    mrp: 175,
    discountPrice: 150,
    unit: 'pack',
    weightKg: 0.2,
    stock: 90,
    originVillage: 'Vapi Industrial Estate',
    originDistrict: 'Valsad',
    originState: 'Gujarat',
    isOrganic: true,
    isFeatured: false,
    rating: 4.8,
    reviewCount: 220,
    images: [
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Herbal pain relief balm with Menthasatva, Gaultheria oil, and Clove for headache & backache.',
    description: 'Fast acting Ayurvedic formulation that penetrates deep into painful muscles and joints. Relieves severe headaches, neck tension, joint aches, and cold-related congestion.',
    tags: ['medicine', 'zandu-balm', 'pain-relief', 'ayurveda', 'herbal', 'headache'],
  },
];

export const seedCatalog = async () => {
  try {
    await connectDB();
    console.log('[Catalog Seeder] Connected to database.');

    // 1. Upsert Categories
    const categoryMap = new Map<string, any>();
    for (const catData of CATEGORIES_DATA) {
      const cat = await Category.findOneAndUpdate(
        { slug: catData.slug },
        { $set: catData },
        { upsert: true, new: true, setDefaultsOnInsert: true }
      );
      categoryMap.set(catData.slug, cat._id);
      console.log(`[Category] Saved: ${cat.name} (${cat.slug})`);
    }

    // 2. Upsert Products
    let addedCount = 0;
    for (const prodData of PRODUCTS_DATA) {
      const categoryId = categoryMap.get(prodData.categorySlug);
      if (!categoryId) continue;

      const { categorySlug, ...rest } = prodData;
      await Product.findOneAndUpdate(
        { slug: prodData.slug },
        {
          $set: {
            ...rest,
            categoryId,
            status: 'active',
          },
        },
        { upsert: true, new: true, setDefaultsOnInsert: true }
      );
      addedCount++;
    }

    console.log(`[Catalog Seeder] Successfully seeded ${CATEGORIES_DATA.length} categories and ${addedCount} products!`);
  } catch (error: any) {
    console.error('[Catalog Seeder Error]', error);
  } finally {
    await disconnectDB();
  }
};

// Execute if run directly
if (process.argv[1] && process.argv[1].replace(/\\/g, '/').includes('seedCatalog')) {
  seedCatalog().then(() => {
    console.log('[Catalog Seeder] Finished.');
    process.exit(0);
  });
}
