import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import { connectDB, disconnectDB } from '../config/db.js';
import {
  User,
  Category,
  Subcategory,
  BusinessAccount,
  Product,
  Order,
  OrderItem,
  Parcel,
  ParcelEvent,
  LogisticsPartner,
  PartnerRoute,
  Vehicle,
  VillageAgent,
  Shipment,
  ShipmentLeg,
  HandoverRecord,
  TrackingEvent,
  Earning,
  Payout,
  Payment,
  Notification,
  KycDocument,
  InventoryLog,
  Coupon,
  Review,
  StoreSettings,
  LogisticsTrip,
} from '../models/index.js';

export const seedDatabase = async (shouldDisconnect: boolean = true) => {
  try {
    if (mongoose.connection.readyState !== 1) {
      await connectDB();
    }
    console.log('[Seed] Connected to database. Purging existing collections...');

    await Promise.all([
      User.deleteMany({}),
      Category.deleteMany({}),
      Subcategory.deleteMany({}),
      BusinessAccount.deleteMany({}),
      Product.deleteMany({}),
      Order.deleteMany({}),
      OrderItem.deleteMany({}),
      Parcel.deleteMany({}),
      ParcelEvent.deleteMany({}),
      LogisticsPartner.deleteMany({}),
      PartnerRoute.deleteMany({}),
      Vehicle.deleteMany({}),
      VillageAgent.deleteMany({}),
      Shipment.deleteMany({}),
      ShipmentLeg.deleteMany({}),
      HandoverRecord.deleteMany({}),
      TrackingEvent.deleteMany({}),
      Earning.deleteMany({}),
      Payout.deleteMany({}),
      Payment.deleteMany({}),
      Notification.deleteMany({}),
      KycDocument.deleteMany({}),
      InventoryLog.deleteMany({}),
      Coupon.deleteMany({}),
      Review.deleteMany({}),
      StoreSettings.deleteMany({}),
    ]);

    console.log('[Seed] Creating 5 Core Users for all portals...');

    // 1. Admin (Store Owner & Company Catalog Controller)
    const adminHashedPassword = await bcrypt.hash('gokul@1996', 10);
    const adminUser = await User.create({
      name: 'Gokul (Admin)',
      phone: '9999900001',
      email: 'gokul@localhaat.in',
      password: adminHashedPassword,
      role: 'admin',
      isActive: true,
      kycStatus: 'verified',
      defaultLocation: {
        addressLine: 'LocalHaat Central Command & Warehouse',
        villageOrCity: 'Varanasi',
        district: 'Varanasi',
        state: 'Uttar Pradesh',
        pincode: '221001',
      },
    });

    // 2. Business / Seller
    const sellerUser = await User.create({
      name: 'Rameshwar Mahato',
      phone: '9999900002',
      email: 'rameshwar.farms@localhaat.in',
      role: 'business',
      isActive: true,
      kycStatus: 'verified',
      defaultLocation: {
        addressLine: 'Kisan Kendra, Sonapur North',
        villageOrCity: 'Sonapur',
        district: 'Varanasi',
        state: 'Uttar Pradesh',
        pincode: '221005',
      },
    });

    // 3. Logistics Partner
    const partnerUser = await User.create({
      name: 'Balwant Singh (Logistics)',
      phone: '9999900003',
      email: 'balwant.transports@localhaat.in',
      role: 'logistics_partner',
      isActive: true,
      kycStatus: 'verified',
      defaultLocation: {
        addressLine: 'GT Road Transporter Hub',
        villageOrCity: 'Ramnagar',
        district: 'Varanasi',
        state: 'Uttar Pradesh',
        pincode: '221008',
      },
    });

    // 4. Village Agent
    const agentUser = await User.create({
      name: 'Sudhir Kumar (Village Haat Agent)',
      phone: '9999900004',
      email: 'sudhir.agent@localhaat.in',
      role: 'village_agent',
      isActive: true,
      kycStatus: 'verified',
      defaultLocation: {
        addressLine: 'Panchayat Haat Drop Point, Main Square',
        villageOrCity: 'Sonapur',
        district: 'Varanasi',
        state: 'Uttar Pradesh',
        pincode: '221005',
      },
    });

    // 5. Customer
    const customerUser = await User.create({
      name: 'Priya Sharma (Customer)',
      phone: '9999900005',
      email: 'priya.sharma@example.com',
      role: 'customer',
      isActive: true,
      kycStatus: 'verified',
      defaultLocation: {
        addressLine: 'House #42, Lane 3, Near Shiv Temple',
        villageOrCity: 'Ramnagar',
        district: 'Varanasi',
        state: 'Uttar Pradesh',
        pincode: '221008',
      },
    });

    console.log('[Seed] Creating Business Account & Fleet Details...');

    const businessAccount = await BusinessAccount.create({
      userId: sellerUser._id,
      businessName: 'Rameshwar Organic Produce & Rural Crafts',
      businessType: 'farmer_producer_org',
      gstin: '09AAECR1234F1Z5',
      pan: 'AAECR1234F',
      registeredAddress: sellerUser.defaultLocation!,
      categorySpecialty: ['Organic Grains', 'Clay Pottery', 'Cold Pressed Oils'],
      bankDetails: {
        accountHolder: 'Rameshwar Mahato',
        accountNumber: '50100234918234',
        ifsc: 'HDFC0001234',
        bankName: 'HDFC Bank Varanasi',
        upiId: 'rameshwar@okaxis',
      },
      rating: 4.9,
      commissionPercentage: 5,
      isVerified: true,
      contactPhone: sellerUser.phone,
      contactEmail: sellerUser.email,
      description: 'Authentic farm-fresh produce and terracotta items hand-crafted by Sonapur artisans.',
    });

    const logisticsPartner = await LogisticsPartner.create({
      userId: partnerUser._id,
      partnerCode: 'LP-1002',
      businessName: 'Kashi Rural Express Logistics',
      partnerType: 'transporter',
      partnerCategory: 'PROFESSIONAL',
      partnerStatus: 'ONLINE',
      verificationStatus: 'VERIFIED',
      phone: '9999900003',
      email: 'balwant.singh@kashirural.in',
      primaryTransportType: 'Bike',
      vehicleNumber: 'UP65-BT-4921',
      capacityKg: 1200,
      serviceAreas: ['Sonapur', 'Ramnagar', 'Chunar', 'Varanasi Rural', 'Mirzapur Outer'],
      rating: 4.95,
      totalTrips: 142,
      totalParcelsDelivered: 580,
      isActive: true,
      isVerified: true,
      isOnline: true,
      currentLocation: {
        latitude: 25.282,
        longitude: 82.998,
        locationName: 'Sonapur Central Hub',
        lastUpdated: new Date(),
      },
      commissionRatePerKm: 12,
      baseDeliveryFee: 40,
    });

    const vehicle = await Vehicle.create({
      partnerId: logisticsPartner._id,
      vehicleType: 'pickup_van',
      registrationNumber: 'UP65-BT-4921',
      modelName: 'Mahindra Bolero Maxi Truck HD',
      maxCapacityKg: 1200,
      currentStatus: 'available',
      currentCoordinates: {
        latitude: 25.282,
        longitude: 82.998,
        lastUpdated: new Date(),
      },
    });

    logisticsPartner.vehicleIds = [vehicle._id as any];
    await logisticsPartner.save();

    const kashiRoute = await PartnerRoute.create({
      partnerId: logisticsPartner._id,
      routeTitle: 'Sonapur Artisan Cluster <-> Ramnagar Village Haat Corridor',
      sourceLocation: sellerUser.defaultLocation!,
      destinationLocation: customerUser.defaultLocation!,
      waypoints: [
        {
          addressLine: 'Chunar Riverbank Hub',
          villageOrCity: 'Chunar',
          district: 'Mirzapur',
          state: 'Uttar Pradesh',
          pincode: '231304',
        },
      ],
      scheduledFrequency: 'daily',
      departureTime: '08:30 AM',
      travelDate: 'Today',
      vehicleType: 'Bike',
      estimatedDurationHours: 2.5,
      totalDistanceKm: 38,
      capacityKg: 1200,
      availableCapacityKg: 1200,
      pricePerKg: 7.5,
      status: 'active',
    });

    await LogisticsTrip.create({
      tripId: 'TRIP-1002',
      partnerId: logisticsPartner._id,
      partnerName: 'Kashi Rural Express Logistics',
      partnerMobile: '9999900003',
      partnerType: 'PROFESSIONAL',
      transportType: 'Bike',
      vehicleId: vehicle._id,
      vehicleType: 'Bike',
      vehicleNumber: 'UP65-BT-4921',
      routeId: kashiRoute._id,
      routeTitle: 'Sonapur ➔ Ramnagar Scheduled Corridor',
      travelDate: 'Today',
      fromLocation: sellerUser.defaultLocation!,
      toLocation: customerUser.defaultLocation!,
      startLocation: {
        name: 'Sonapur',
        villageOrCity: 'Sonapur',
        address: sellerUser.defaultLocation?.addressLine || 'Sonapur Haat Mandi',
        departureTime: '08:30 AM',
        status: 'PENDING',
      },
      finalDestination: {
        name: 'Ramnagar',
        villageOrCity: 'Ramnagar',
        address: customerUser.defaultLocation?.addressLine || 'Ramnagar Haat Drop',
        expectedArrival: '11:00 AM',
        status: 'UPCOMING',
      },
      waypoints: [
        {
          addressLine: 'Chunar Riverbank Hub',
          villageOrCity: 'Chunar',
          district: 'Mirzapur',
          state: 'Uttar Pradesh',
          pincode: '231304',
        },
      ],
      stops: [
        {
          stopId: 'STOP-1',
          stopOrder: 1,
          name: 'Chunar',
          villageOrCity: 'Chunar',
          address: 'Chunar Riverbank Hub',
          expectedArrival: '09:30 AM',
          expectedDeparture: '09:40 AM',
          waitingMinutes: 10,
          status: 'UPCOMING',
        },
      ],
      departureTime: '08:30 AM',
      expectedArrival: '11:00 AM',
      tripStatus: 'SCHEDULED',
      totalCapacityKg: 1200,
      usedCapacityKg: 0,
      availableCapacityKg: 1200,
      pricePerKg: 7.5,
      parcelIds: [],
      activeParcelCount: 0,
      notes: 'Daily scheduled route between Sonapur and Ramnagar haat cluster.',
    });

    const villageAgent = await VillageAgent.create({
      userId: agentUser._id,
      villageName: 'Sonapur & Ramnagar Haat Cluster',
      hubCode: 'VH-UP-0042',
      servingVillages: ['Sonapur', 'Ramnagar', 'Chunar Outer', 'Kachhwa'],
      hubAddress: agentUser.defaultLocation!,
      commissionPerDelivery: 30,
      activeParcelsCount: 2,
      cashInHand: 1450,
      isAvailable: true,
      rating: 4.95,
      totalDelivered: 215,
      workingHours: '07:30 AM - 08:00 PM',
    });

    console.log('[Seed] Creating Store Settings...');
    await StoreSettings.create({
      storeName: 'LocalHaat Direct Store',
      storeTagline: 'Pure, Village-Sourced Staples & Heritage Essentials Delivered Direct',
      storeEmail: 'orders@localhaat.in',
      storePhone: '+91 9999900001',
      address: {
        street: 'Central Haat Depot, GT Road',
        city: 'Varanasi',
        district: 'Varanasi',
        state: 'Uttar Pradesh',
        pincode: '221001',
      },
      currency: 'INR',
      taxGstRate: 5,
      defaultDeliveryFee: 40,
      freeDeliveryThreshold: 499,
      lowStockThresholdDefault: 5,
      enableCod: true,
      enableOnlinePayment: true,
      storeStatus: 'OPEN',
      supportHours: 'Mon - Sun: 7:00 AM - 9:00 PM',
    });

    console.log('[Seed] Creating 7 Clean Admin Company Store Categories...');
    // Categories matching user specification: Rice, Daal, Aata, FMCG, Household, Personal Care, Spices
    const categories = await Category.create([
      {
        name: 'Rice',
        slug: 'rice',
        description: 'Authentic aged Basmati, indigenous Govind Bhog, and organic traditional rice grains',
        icon: '🌾',
        image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
        isActive: true,
        displayOrder: 1,
        parentCategoryId: null,
      },
      {
        name: 'Daal',
        slug: 'daal',
        description: 'Unpolished desi toor, yellow moong, split urad, and protein-packed chana daal',
        icon: '🍲',
        image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
        isActive: true,
        displayOrder: 2,
        parentCategoryId: null,
      },
      {
        name: 'Aata',
        slug: 'aata',
        description: 'Chakki-fresh stone ground Sharbati wheat, roasted chana sattu, and multigrain flours',
        icon: '🥣',
        image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
        isActive: true,
        displayOrder: 3,
        parentCategoryId: null,
      },
      {
        name: 'FMCG',
        slug: 'fmcg',
        description: 'Wood-churned cold-pressed oils, pure A2 Vedic Gir cow ghee, and natural jaggery blocks',
        icon: '🛒',
        image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',
        isActive: true,
        displayOrder: 4,
        parentCategoryId: null,
      },
      {
        name: 'Household',
        slug: 'household',
        description: 'Handmade terracotta biryani handis, chai kulhads, pre-seasoned cast iron tawas, and copper bottles',
        icon: '🏺',
        image: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=600&q=80',
        isActive: true,
        displayOrder: 5,
        parentCategoryId: null,
      },
      {
        name: 'Personal Care',
        slug: 'personal-care',
        description: 'Raw wild forest honey, handmade cold-process neem soaps, and Ayurvedic skincare essentials',
        icon: '🌿',
        image: 'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&w=600&q=80',
        isActive: true,
        displayOrder: 6,
        parentCategoryId: null,
      },
      {
        name: 'Spices',
        slug: 'spices',
        description: 'Single-origin Lakadong turmeric, Tellicherry black peppercorns, and whole aromatic spice blends',
        icon: '🌶️',
        image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80',
        isActive: true,
        displayOrder: 7,
        parentCategoryId: null,
      },
    ]);

    console.log('[Seed] Creating Subcategories for each category...');
    const subcategories = await Subcategory.create([
      // Rice (cat 0)
      { name: 'Basmati Rice', slug: 'basmati-rice', categoryId: categories[0]._id, isActive: true, displayOrder: 1 },
      { name: 'Govind Bhog & Traditional Rice', slug: 'govind-bhog-rice', categoryId: categories[0]._id, isActive: true, displayOrder: 2 },
      { name: 'Brown & Red Rice', slug: 'brown-red-rice', categoryId: categories[0]._id, isActive: true, displayOrder: 3 },

      // Daal (cat 1)
      { name: 'Toor / Arhar Daal', slug: 'toor-arhar-daal', categoryId: categories[1]._id, isActive: true, displayOrder: 1 },
      { name: 'Moong & Urad Daal', slug: 'moong-urad-daal', categoryId: categories[1]._id, isActive: true, displayOrder: 2 },
      { name: 'Chana Daal', slug: 'chana-daal', categoryId: categories[1]._id, isActive: true, displayOrder: 3 },

      // Aata (cat 2)
      { name: 'Chakki Sharbati Wheat Aata', slug: 'sharbati-wheat-aata', categoryId: categories[2]._id, isActive: true, displayOrder: 1 },
      { name: 'Roasted Desi Chana Sattu', slug: 'desi-chana-sattu', categoryId: categories[2]._id, isActive: true, displayOrder: 2 },
      { name: 'Multigrain & Specialty Flours', slug: 'multigrain-flours', categoryId: categories[2]._id, isActive: true, displayOrder: 3 },

      // FMCG (cat 3)
      { name: 'Wood-Pressed Cooking Oils', slug: 'wood-pressed-oils', categoryId: categories[3]._id, isActive: true, displayOrder: 1 },
      { name: 'A2 Gir Cow Ghee', slug: 'gir-cow-ghee', categoryId: categories[3]._id, isActive: true, displayOrder: 2 },
      { name: 'Desi Gur & Natural Sweeteners', slug: 'desi-gur-sweeteners', categoryId: categories[3]._id, isActive: true, displayOrder: 3 },

      // Household (cat 4)
      { name: 'Terracotta & Clay Cookware', slug: 'terracotta-cookware', categoryId: categories[4]._id, isActive: true, displayOrder: 1 },
      { name: 'Pre-Seasoned Cast Iron', slug: 'cast-iron-cookware', categoryId: categories[4]._id, isActive: true, displayOrder: 2 },
      { name: 'Ayurvedic Copper Utensils', slug: 'ayurvedic-copper', categoryId: categories[4]._id, isActive: true, displayOrder: 3 },

      // Personal Care (cat 5)
      { name: 'Raw Forest Honey', slug: 'raw-forest-honey', categoryId: categories[5]._id, isActive: true, displayOrder: 1 },
      { name: 'Natural Herbal Soaps', slug: 'herbal-soaps', categoryId: categories[5]._id, isActive: true, displayOrder: 2 },
      { name: 'Ayurvedic Wellness Care', slug: 'ayurvedic-wellness', categoryId: categories[5]._id, isActive: true, displayOrder: 3 },

      // Spices (cat 6)
      { name: 'Whole Heritage Spices', slug: 'whole-heritage-spices', categoryId: categories[6]._id, isActive: true, displayOrder: 1 },
      { name: 'Ground Spices & Masalas', slug: 'ground-spices', categoryId: categories[6]._id, isActive: true, displayOrder: 2 },
      { name: 'High-Curcumin Turmeric', slug: 'lakadong-turmeric', categoryId: categories[6]._id, isActive: true, displayOrder: 3 },
    ]);

    console.log('[Seed] Creating 28 Pure Admin Company Store Products (All owned by Admin)...');
    const products = await Product.create([
      /* ==================== 1. RICE (4 Products) ==================== */
      {
        title: 'Royal Aged 1121 Basmati Rice (Extra Long Grain, 5kg)',
        sku: 'LH-RICE-01',
        slug: 'royal-aged-1121-basmati-rice-5kg',
        description: 'Naturally aged for two full years in Himalayan foothills. Slender, pearlescent extra-long grains that elongate to double length upon steaming.',
        shortDescription: '2-year naturally aged 1121 extra-long grain fragrant basmati rice.',
        categoryId: categories[0]._id,
        subcategoryId: subcategories[0]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 750,
        price: 680,
        discountPrice: 599,
        stock: 65,
        lowStockThreshold: 10,
        unit: '5kg pack',
        weightKg: 5.0,
        images: [
          'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=800&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80',
        originVillage: 'Dehradun Valley Cluster',
        originDistrict: 'Varanasi Regional Depot',
        originState: 'Uttar Pradesh',
        status: 'active',
        isFeatured: true,
        isOrganic: false,
        rating: 4.9,
        reviewCount: 94,
        tags: ['rice', 'basmati', 'biryani', 'aged', 'grain'],
      },
      {
        title: 'Heritage Govind Bhog Sweet Aromatic Rice (2kg)',
        sku: 'LH-RICE-02',
        slug: 'heritage-govind-bhog-aromatic-rice-2kg',
        description: 'Short, buttery, and intensely fragrant indigenous Govind Bhog rice. Ideal for authentic Bengali Payesh, village kheer, and daily bhog prasad.',
        shortDescription: 'Short aromatic grain ideal for traditional kheer, pulao, and bhog.',
        categoryId: categories[0]._id,
        subcategoryId: subcategories[1]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 290,
        price: 260,
        discountPrice: 220,
        stock: 48,
        lowStockThreshold: 8,
        unit: '2kg pack',
        weightKg: 2.0,
        images: [
          'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=800&q=80',
        originVillage: 'Sonapur Agricultural Belt',
        originDistrict: 'Varanasi',
        originState: 'Uttar Pradesh',
        status: 'active',
        isOrganic: true,
        rating: 4.8,
        reviewCount: 43,
        tags: ['rice', 'govindbhog', 'kheer', 'aromatic', 'organic'],
      },
      {
        title: 'Organic Himalayan High-Altitude Red Rice (1kg)',
        sku: 'LH-RICE-03',
        slug: 'organic-himalayan-red-rice-1kg',
        description: 'Ancient heirloom whole grain rice rich in antioxidants, anthocyanins, and dietary fiber. Earthy, nutty texture that pairs wonderfully with curries.',
        shortDescription: 'Unpolished antioxidant-rich Himalayan whole red rice.',
        categoryId: categories[0]._id,
        subcategoryId: subcategories[2]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 220,
        price: 190,
        discountPrice: 165,
        stock: 35,
        lowStockThreshold: 5,
        unit: '1kg pack',
        weightKg: 1.0,
        images: [
          'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80',
        ],
        originVillage: 'Purvanchal Organic Hub',
        originDistrict: 'Varanasi',
        originState: 'Uttar Pradesh',
        status: 'active',
        isOrganic: true,
        rating: 4.7,
        reviewCount: 29,
        tags: ['rice', 'red-rice', 'organic', 'wholegrain', 'fitness'],
      },
      {
        title: 'Unpolished Fiber-Rich Brown Basmati Rice (1kg)',
        sku: 'LH-RICE-04',
        slug: 'unpolished-brown-basmati-rice-1kg',
        description: 'Complete bran intact long-grain brown basmati. Low glycemic index staple that provides slow-burning energy and wholesome nutrition.',
        shortDescription: '100% whole grain brown basmati with natural bran intact.',
        categoryId: categories[0]._id,
        subcategoryId: subcategories[2]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 200,
        price: 180,
        discountPrice: 155,
        stock: 40,
        lowStockThreshold: 5,
        unit: '1kg pack',
        weightKg: 1.0,
        images: [
          'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=800&q=80',
        ],
        originVillage: 'Ramnagar Farmers Hub',
        originDistrict: 'Varanasi',
        originState: 'Uttar Pradesh',
        status: 'active',
        isOrganic: true,
        rating: 4.8,
        reviewCount: 36,
        tags: ['rice', 'brown-rice', 'healthy', 'diet', 'unpolished'],
      },

      /* ==================== 2. DAAL (4 Products) ==================== */
      {
        title: 'Desi Unpolished Arhar / Toor Daal (Purity Assured, 1kg)',
        sku: 'LH-DAAL-01',
        slug: 'desi-unpolished-arhar-toor-daal-1kg',
        description: 'Pure village farm toor daal with zero chemical oil polishing and zero artificial colors. Cooks smoothly into rich, hearty golden tadka.',
        shortDescription: 'Naturally sun-dried, chemical-free raw Arhar dal.',
        categoryId: categories[1]._id,
        subcategoryId: subcategories[3]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 220,
        price: 195,
        discountPrice: 175,
        stock: 80,
        lowStockThreshold: 15,
        unit: '1kg pack',
        weightKg: 1.0,
        images: [
          'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
        originVillage: 'Sonapur Agricultural Belt',
        originDistrict: 'Varanasi',
        originState: 'Uttar Pradesh',
        status: 'active',
        isFeatured: true,
        isOrganic: true,
        rating: 4.9,
        reviewCount: 112,
        tags: ['daal', 'toor', 'arhar', 'pulses', 'unpolished'],
      },
      {
        title: 'Organic Yellow Moong Daal (Split, 1kg)',
        sku: 'LH-DAAL-02',
        slug: 'organic-yellow-moong-daal-1kg',
        description: 'Easily digestible, high protein split yellow moong cultivated by smallholder farmers. The gold standard for light khichdi and nourishing soup.',
        shortDescription: 'Quick cooking, light and wholesome split moong lentils.',
        categoryId: categories[1]._id,
        subcategoryId: subcategories[4]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 190,
        price: 170,
        discountPrice: 150,
        stock: 55,
        lowStockThreshold: 10,
        unit: '1kg pack',
        weightKg: 1.0,
        images: [
          'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
        ],
        originVillage: 'Chunar Riverbank Farms',
        originDistrict: 'Mirzapur',
        originState: 'Uttar Pradesh',
        status: 'active',
        isOrganic: true,
        rating: 4.8,
        reviewCount: 58,
        tags: ['daal', 'moong', 'khichdi', 'protein', 'digestible'],
      },
      {
        title: 'Desi Whole Chana Daal (Village Cleaned, 1kg)',
        sku: 'LH-DAAL-03',
        slug: 'desi-whole-chana-daal-1kg',
        description: 'Bold Bengal gram split daal sourced fresh from Purvanchal harvest. Robust nutty bite, perfect for poori chana, dal fry, and puran poli.',
        shortDescription: 'High dietary fiber split Bengal gram lentils.',
        categoryId: categories[1]._id,
        subcategoryId: subcategories[5]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 160,
        price: 140,
        discountPrice: 125,
        stock: 70,
        lowStockThreshold: 10,
        unit: '1kg pack',
        weightKg: 1.0,
        images: [
          'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
        ],
        originVillage: 'Sonapur Agricultural Belt',
        originDistrict: 'Varanasi',
        originState: 'Uttar Pradesh',
        status: 'active',
        isOrganic: true,
        rating: 4.8,
        reviewCount: 49,
        tags: ['daal', 'chana', 'bengalgram', 'fiber', 'dal-fry'],
      },
      {
        title: 'Traditional Whole Black Urad Daal (1kg)',
        sku: 'LH-DAAL-04',
        slug: 'traditional-whole-black-urad-daal-1kg',
        description: 'Rich, iron-loaded black gram lentils. The essential ingredient for authentic creamy Dal Makhani, village bedmi poori stuffing, and crispy vadas.',
        shortDescription: 'Natural whole black gram for slow-cooked Dal Makhani.',
        categoryId: categories[1]._id,
        subcategoryId: subcategories[4]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 180,
        price: 160,
        discountPrice: 145,
        stock: 50,
        lowStockThreshold: 8,
        unit: '1kg pack',
        weightKg: 1.0,
        images: [
          'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
        ],
        originVillage: 'Sonapur Agricultural Belt',
        originDistrict: 'Varanasi',
        originState: 'Uttar Pradesh',
        status: 'active',
        isOrganic: true,
        rating: 4.9,
        reviewCount: 67,
        tags: ['daal', 'urad', 'dal-makhani', 'iron', 'desi'],
      },

      /* ==================== 3. AATA (4 Products) ==================== */
      {
        title: 'Chakki Fresh Sharbati Whole Wheat Aata (Stone Ground, 5kg)',
        sku: 'LH-AATA-01',
        slug: 'chakki-fresh-sharbati-whole-wheat-aata-5kg',
        description: '100% pure Madhya Pradesh Sharbati golden wheat milled fresh in traditional stone chakkis without heat build-up. Yields super-soft, sweet rotis that stay tender for hours.',
        shortDescription: 'Cold stone-ground 100% Sharbati wheat flour with intact bran.',
        categoryId: categories[2]._id,
        subcategoryId: subcategories[6]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 360,
        price: 320,
        discountPrice: 280,
        stock: 90,
        lowStockThreshold: 15,
        unit: '5kg bag',
        weightKg: 5.0,
        images: [
          'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=800&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
        originVillage: 'Sonapur Chakki Mills',
        originDistrict: 'Varanasi',
        originState: 'Uttar Pradesh',
        status: 'active',
        isFeatured: true,
        isOrganic: true,
        rating: 5.0,
        reviewCount: 145,
        tags: ['aata', 'flour', 'wheat', 'sharbati', 'roti', 'chakki'],
      },
      {
        title: 'Traditional Roasted Desi Chana Sattu (Ground Flour, 1kg)',
        sku: 'LH-AATA-02',
        slug: 'roasted-desi-chana-sattu-1kg',
        description: 'Wood-fired roasted Bengal gram ground into aromatic sattu powder. The celebrated high-protein stamina superfood of Purvanchal & Bihar for sharbat and litti.',
        shortDescription: 'Protein-packed roasted chana sattu for healthy drinks and litti.',
        categoryId: categories[2]._id,
        subcategoryId: subcategories[7]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 230,
        price: 210,
        discountPrice: 185,
        stock: 60,
        lowStockThreshold: 10,
        unit: '1kg pack',
        weightKg: 1.0,
        images: [
          'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80',
        originVillage: 'Ramnagar Farmers Hub',
        originDistrict: 'Varanasi',
        originState: 'Uttar Pradesh',
        status: 'active',
        isOrganic: true,
        rating: 4.9,
        reviewCount: 78,
        tags: ['sattu', 'aata', 'chana', 'protein', 'superfood', 'bihar'],
      },
      {
        title: 'Nutritious 7-Grain Multigrain Aata (High Fiber, 2kg)',
        sku: 'LH-AATA-03',
        slug: 'nutritious-7-grain-multigrain-aata-2kg',
        description: 'Harmonious blend of Sharbati wheat, roasted chana, ragi, jowar, bajra, soy, and oats. Provides rich digestive fiber and diabetic-friendly slow carbohydrates.',
        shortDescription: 'Balanced blend of 7 ancient grains and millets.',
        categoryId: categories[2]._id,
        subcategoryId: subcategories[8]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 210,
        price: 180,
        discountPrice: 160,
        stock: 45,
        lowStockThreshold: 8,
        unit: '2kg pack',
        weightKg: 2.0,
        images: [
          'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
        ],
        originVillage: 'Sonapur Chakki Mills',
        originDistrict: 'Varanasi',
        originState: 'Uttar Pradesh',
        status: 'active',
        isOrganic: true,
        rating: 4.8,
        reviewCount: 52,
        tags: ['aata', 'multigrain', 'ragi', 'jowar', 'fiber', 'healthy'],
      },
      {
        title: 'Pure Stone-Ground Yellow Makka (Corn) Aata (1kg)',
        sku: 'LH-AATA-04',
        slug: 'pure-stone-ground-makka-corn-aata-1kg',
        description: 'Sun-ripened yellow corn grain stone-milled coarse for authentic winter Makki di Roti. Earthy sweet aroma and golden rustic texture.',
        shortDescription: 'Pure stone ground yellow corn meal for winter rotis.',
        categoryId: categories[2]._id,
        subcategoryId: subcategories[8]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 110,
        price: 95,
        discountPrice: 80,
        stock: 40,
        lowStockThreshold: 5,
        unit: '1kg pack',
        weightKg: 1.0,
        images: [
          'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=800&q=80',
        ],
        originVillage: 'Sonapur Agricultural Belt',
        originDistrict: 'Varanasi',
        originState: 'Uttar Pradesh',
        status: 'active',
        isOrganic: true,
        rating: 4.7,
        reviewCount: 31,
        tags: ['aata', 'makka', 'corn', 'winter', 'sarson-ka-saag'],
      },

      /* ==================== 4. FMCG (4 Products) ==================== */
      {
        title: 'Cold-Pressed Kachi Ghani Mustard Oil (Wood Expeller, 1L)',
        sku: 'LH-FMCG-01',
        slug: 'cold-pressed-kachi-ghani-mustard-oil-1l',
        description: 'Extracted slowly from yellow and black mustard seeds in village wooden kolhu at ambient temperatures. Strong pungent aroma, rich in Omega-3 and natural antioxidants.',
        shortDescription: 'Pungent cold-pressed sarson oil extracted in traditional wooden kolhu.',
        categoryId: categories[3]._id,
        subcategoryId: subcategories[9]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 260,
        price: 240,
        discountPrice: 210,
        stock: 75,
        lowStockThreshold: 15,
        unit: '1 Litre bottle',
        weightKg: 1.1,
        images: [
          'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1589927986089-35812388d1f4?auto=format&fit=crop&w=800&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=800&q=80',
        originVillage: 'Sonapur Kolhu Guild',
        originDistrict: 'Varanasi',
        originState: 'Uttar Pradesh',
        status: 'active',
        isFeatured: true,
        isOrganic: true,
        rating: 4.9,
        reviewCount: 138,
        tags: ['fmcg', 'oil', 'mustard', 'sarson', 'cold-pressed', 'kachi-ghani'],
      },
      {
        title: 'Pure A2 Vedic Gir Cow Bilona Ghee (Hand-Churned, 500ml)',
        sku: 'LH-FMCG-02',
        slug: 'pure-a2-bilona-gir-cow-ghee-500ml',
        description: 'Prepared strictly by traditional Vedic bilona method from curd of free-grazing Gir cows. Rich golden granular texture with heavenly nostalgic aroma and zero additives.',
        shortDescription: 'Cultured A2 cow bilona ghee packed with gut-healing butyric acid.',
        categoryId: categories[3]._id,
        subcategoryId: subcategories[10]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 1050,
        price: 950,
        discountPrice: 850,
        stock: 35,
        lowStockThreshold: 6,
        unit: '500ml glass jar',
        weightKg: 0.7,
        images: [
          'https://images.unsplash.com/photo-1589927986089-35812388d1f4?auto=format&fit=crop&w=800&q=80',
        ],
        originVillage: 'Kashi Vedic Goshala',
        originDistrict: 'Varanasi',
        originState: 'Uttar Pradesh',
        status: 'active',
        isFeatured: true,
        isOrganic: true,
        rating: 5.0,
        reviewCount: 189,
        tags: ['fmcg', 'ghee', 'a2', 'bilona', 'gir-cow', 'ayurvedic', 'pure'],
      },
      {
        title: 'Wood-Pressed Virgin Groundnut Peanut Oil (1L Bottle)',
        sku: 'LH-FMCG-03',
        slug: 'wood-pressed-virgin-groundnut-oil-1l',
        description: 'Gently cold-pressed from native Saurashtra peanuts in slow wooden expeller. Delicate nutty flavor, high smoking point ideal for daily frying and tadka.',
        shortDescription: '100% unrefined natural peanut oil with sweet aroma.',
        categoryId: categories[3]._id,
        subcategoryId: subcategories[9]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 320,
        price: 290,
        discountPrice: 260,
        stock: 50,
        lowStockThreshold: 8,
        unit: '1 Litre bottle',
        weightKg: 1.1,
        images: [
          'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=800&q=80',
        ],
        originVillage: 'Sonapur Kolhu Guild',
        originDistrict: 'Varanasi',
        originState: 'Uttar Pradesh',
        status: 'active',
        isOrganic: true,
        rating: 4.8,
        reviewCount: 46,
        tags: ['fmcg', 'oil', 'groundnut', 'peanut', 'cooking-oil', 'unrefined'],
      },
      {
        title: 'Desi Organic Sugarcane Gur Jaggery Block (Solid, 1kg)',
        sku: 'LH-FMCG-04',
        slug: 'organic-sugarcane-gur-jaggery-1kg',
        description: 'Handmade sugarcane gur cooked slowly over village bagasse bhattis without baking soda or chemical bleach. Rich in natural iron, calcium, and minerals.',
        shortDescription: 'Unrefined mineral-rich chemical-free solid sugarcane jaggery.',
        categoryId: categories[3]._id,
        subcategoryId: subcategories[11]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 180,
        price: 160,
        discountPrice: 140,
        stock: 85,
        lowStockThreshold: 12,
        unit: '1kg solid block',
        weightKg: 1.0,
        images: [
          'https://images.unsplash.com/photo-1608686207856-001b95cf60ca?auto=format&fit=crop&w=800&q=80',
        ],
        originVillage: 'Sonapur Cane Farms',
        originDistrict: 'Varanasi',
        originState: 'Uttar Pradesh',
        status: 'active',
        isOrganic: true,
        rating: 4.9,
        reviewCount: 75,
        tags: ['fmcg', 'jaggery', 'gur', 'iron', 'organic', 'sweetener'],
      },

      /* ==================== 5. HOUSEHOLD (4 Products) ==================== */
      {
        title: 'Handcrafted Clay Biryani Handi with Lid (Lead-Free, 2L)',
        sku: 'LH-HH-01',
        slug: 'handcrafted-clay-biryani-handi-2l',
        description: 'Shaped manually by master potters from riverbank clay and baked in slow wood kilns. Micro-porous walls circulate heat evenly, infusing food with delicious earthy flavor.',
        shortDescription: '100% lead-free non-toxic traditional earthenware cooking handi.',
        categoryId: categories[4]._id,
        subcategoryId: subcategories[12]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 450,
        price: 380,
        discountPrice: 340,
        stock: 35,
        lowStockThreshold: 5,
        unit: '2 Litre Pot with Lid',
        weightKg: 1.6,
        images: [
          'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
        originVillage: 'Chunar Pottery Cluster',
        originDistrict: 'Mirzapur',
        originState: 'Uttar Pradesh',
        status: 'active',
        isFeatured: true,
        isOrganic: false,
        rating: 4.9,
        reviewCount: 62,
        tags: ['household', 'cookware', 'handi', 'clay', 'terracotta', 'mitti'],
      },
      {
        title: 'Traditional Terracotta Chai Kulhad (Wood-Baked, Set of 6)',
        sku: 'LH-HH-02',
        slug: 'terracotta-chai-kulhad-set-6',
        description: 'Natural clay earthen kulhads seasoned over wood smoke. Retains heat and adds the authentic village kulhad fragrance to masala tea and lassi.',
        shortDescription: 'Eco-friendly biodegradable earthen tea cups set of 6.',
        categoryId: categories[4]._id,
        subcategoryId: subcategories[12]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 220,
        price: 180,
        discountPrice: 150,
        stock: 65,
        lowStockThreshold: 10,
        unit: 'Set of 6 cups',
        weightKg: 0.9,
        images: [
          'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
        ],
        originVillage: 'Chunar Pottery Cluster',
        originDistrict: 'Mirzapur',
        originState: 'Uttar Pradesh',
        status: 'active',
        isOrganic: false,
        rating: 4.8,
        reviewCount: 98,
        tags: ['household', 'kulhad', 'chai', 'tea', 'clay', 'terracotta'],
      },
      {
        title: 'Pre-Seasoned Heavy Cast Iron Dosa & Roti Tawa (10 Inch)',
        sku: 'LH-HH-03',
        slug: 'pre-seasoned-cast-iron-tawa-10inch',
        description: 'Heavy 4mm thick virgin cast iron tawa pre-seasoned with organic til oil. Delivers superior heat retention for crispy golden dosas, parathas, and rotis.',
        shortDescription: 'Toxin-free heavy gauge cast iron tawa seasoned with natural oils.',
        categoryId: categories[4]._id,
        subcategoryId: subcategories[13]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 999,
        price: 890,
        discountPrice: 750,
        stock: 28,
        lowStockThreshold: 5,
        unit: '1 Piece (2.4kg)',
        weightKg: 2.4,
        images: [
          'https://images.unsplash.com/photo-1584990347449-a2e63cb73c9f?auto=format&fit=crop&w=800&q=80',
        ],
        originVillage: 'Chunar Crafts Hub',
        originDistrict: 'Mirzapur',
        originState: 'Uttar Pradesh',
        status: 'active',
        isOrganic: false,
        rating: 4.9,
        reviewCount: 71,
        tags: ['household', 'castiron', 'tawa', 'cookware', 'non-stick', 'dosa'],
      },
      {
        title: 'Hand-Hammered Pure Ayurvedic Copper Water Bottle (1000ml)',
        sku: 'LH-HH-04',
        slug: 'hand-hammered-copper-water-bottle-1l',
        description: 'Crafted from 99.4% pure food-grade copper with seamless joint-less body. Naturally balances the three doshas and enriches drinking water with vital copper ions.',
        shortDescription: 'Leakproof hammered copper vessel for healthy drinking water.',
        categoryId: categories[4]._id,
        subcategoryId: subcategories[14]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 950,
        price: 799,
        discountPrice: 650,
        stock: 40,
        lowStockThreshold: 8,
        unit: '1000ml bottle',
        weightKg: 0.45,
        images: [
          'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80',
        ],
        originVillage: 'Kashi Thatheri Bazaar',
        originDistrict: 'Varanasi',
        originState: 'Uttar Pradesh',
        status: 'active',
        isOrganic: false,
        rating: 4.9,
        reviewCount: 84,
        tags: ['household', 'copper', 'water-bottle', 'ayurveda', 'tambha'],
      },

      /* ==================== 6. PERSONAL CARE (4 Products) ==================== */
      {
        title: 'Raw Multi-Flora Wild Forest Honey (Unpasteurized, 500g)',
        sku: 'LH-PC-01',
        slug: 'raw-multi-flora-wild-forest-honey-500g',
        description: 'Single-source wild forest honey ethically extracted from indigenous honeycombs. Free from heat processing, ultra-filtration, or corn syrup.',
        shortDescription: '100% pure raw unheated forest honey loaded with natural pollens.',
        categoryId: categories[5]._id,
        subcategoryId: subcategories[15]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 520,
        price: 450,
        discountPrice: 390,
        stock: 55,
        lowStockThreshold: 10,
        unit: '500g glass jar',
        weightKg: 0.8,
        images: [
          'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&w=800&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?auto=format&fit=crop&w=800&q=80',
        originVillage: 'Sonapur Forest Cluster',
        originDistrict: 'Varanasi',
        originState: 'Uttar Pradesh',
        status: 'active',
        isFeatured: true,
        isOrganic: true,
        rating: 5.0,
        reviewCount: 164,
        tags: ['personal-care', 'honey', 'wild', 'raw', 'immunity', 'ayurveda'],
      },
      {
        title: 'Handmade Cold-Process Neem & Tulsi Herbal Soap (Pack of 3)',
        sku: 'LH-PC-02',
        slug: 'handmade-neem-tulsi-herbal-soap-3pack',
        description: 'Cured over 6 weeks with cold-pressed virgin coconut and sesame oils, fresh ground neem leaves, and sacred holy basil oil. Soothes acne and irritated skin.',
        shortDescription: 'Ayurvedic antibacterial neem soap bars with zero SLS or parabens.',
        categoryId: categories[5]._id,
        subcategoryId: subcategories[16]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 350,
        price: 299,
        discountPrice: 249,
        stock: 60,
        lowStockThreshold: 10,
        unit: 'Pack of 3 bars (375g)',
        weightKg: 0.4,
        images: [
          'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&w=800&q=80',
        ],
        originVillage: 'Sonapur Women SHG Hub',
        originDistrict: 'Varanasi',
        originState: 'Uttar Pradesh',
        status: 'active',
        isOrganic: true,
        rating: 4.9,
        reviewCount: 92,
        tags: ['personal-care', 'soap', 'neem', 'tulsi', 'bath', 'handmade'],
      },
      {
        title: 'Pure Ayurvedic Kumkumadi Tailam Radiant Facial Oil (30ml)',
        sku: 'LH-PC-03',
        slug: 'kumkumadi-tailam-radiant-facial-oil-30ml',
        description: 'Classical Ayurvedic formulation prepared with Kashmiri saffron stigma, red sandalwood, vetiver, and 26 sacred herbs in sesame oil base. Restores skin glow.',
        shortDescription: 'Precious saffron Ayurvedic elixir for natural luminous radiance.',
        categoryId: categories[5]._id,
        subcategoryId: subcategories[17]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 650,
        price: 550,
        discountPrice: 480,
        stock: 30,
        lowStockThreshold: 5,
        unit: '30ml dropper bottle',
        weightKg: 0.15,
        images: [
          'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&w=800&q=80',
        ],
        originVillage: 'Kashi Ayurveda Pharmacy',
        originDistrict: 'Varanasi',
        originState: 'Uttar Pradesh',
        status: 'active',
        isOrganic: true,
        rating: 4.9,
        reviewCount: 57,
        tags: ['personal-care', 'facial-oil', 'kumkumadi', 'saffron', 'ayurveda'],
      },
      {
        title: 'Organic Aloe Vera & Rose Water Hydrating Gel (200g)',
        sku: 'LH-PC-04',
        slug: 'organic-aloe-vera-rose-water-gel-200g',
        description: 'Freshly harvested inner-leaf aloe barbadensis gel blended with steam-distilled native Damask rose water. Lightweight hydration for glowing skin and cooling scalp.',
        shortDescription: 'Pure multipurpose moisturizing gel with soothing Damask rose.',
        categoryId: categories[5]._id,
        subcategoryId: subcategories[17]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 260,
        price: 220,
        discountPrice: 190,
        stock: 45,
        lowStockThreshold: 8,
        unit: '200g jar',
        weightKg: 0.25,
        images: [
          'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&w=800&q=80',
        ],
        originVillage: 'Sonapur Wellness SHG',
        originDistrict: 'Varanasi',
        originState: 'Uttar Pradesh',
        status: 'active',
        isOrganic: true,
        rating: 4.8,
        reviewCount: 41,
        tags: ['personal-care', 'aloe-vera', 'rose-water', 'moisturizer', 'gel'],
      },

      /* ==================== 7. SPICES (4 Products) ==================== */
      {
        title: 'High-Curcumin Lakadong Turmeric Powder (7.5% Curcumin, 250g)',
        sku: 'LH-SP-01',
        slug: 'lakadong-turmeric-powder-250g',
        description: 'Cultivated in pristine Meghalaya soil with supreme 7.5% natural curcumin concentration. Vivid deep golden hue and unmatched anti-inflammatory potency.',
        shortDescription: 'World-renowned high curcumin natural golden turmeric powder.',
        categoryId: categories[6]._id,
        subcategoryId: subcategories[20]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 320,
        price: 280,
        discountPrice: 240,
        stock: 80,
        lowStockThreshold: 12,
        unit: '250g airtight tin',
        weightKg: 0.35,
        images: [
          'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80',
        originVillage: 'Purvanchal Herb Hub',
        originDistrict: 'Varanasi',
        originState: 'Uttar Pradesh',
        status: 'active',
        isFeatured: true,
        isOrganic: true,
        rating: 5.0,
        reviewCount: 178,
        tags: ['spices', 'haldi', 'turmeric', 'curcumin', 'lakadong', 'organic'],
      },
      {
        title: 'Tellicherry Sun-Dried Whole Black Peppercorns (200g)',
        sku: 'LH-SP-02',
        slug: 'tellicherry-whole-black-peppercorns-200g',
        description: 'Handpicked extra-bold peppercorns sun-dried on clean mats. Distinct fruity complexity followed by an intense warming, robust pepper kick.',
        shortDescription: 'Jumbo whole grade Tellicherry black peppercorns.',
        categoryId: categories[6]._id,
        subcategoryId: subcategories[18]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 390,
        price: 340,
        discountPrice: 290,
        stock: 60,
        lowStockThreshold: 10,
        unit: '200g glass jar',
        weightKg: 0.35,
        images: [
          'https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=800&q=80',
        ],
        originVillage: 'Purvanchal Spice Mandi',
        originDistrict: 'Varanasi',
        originState: 'Uttar Pradesh',
        status: 'active',
        isOrganic: true,
        rating: 4.9,
        reviewCount: 88,
        tags: ['spices', 'peppercorns', 'kalimirch', 'tellicherry', 'whole-spice'],
      },
      {
        title: 'Royal Shahi Khada Garam Masala Blend (Hand-Selected, 100g)',
        sku: 'LH-SP-03',
        slug: 'royal-shahi-khada-garam-masala-100g',
        description: 'Exquisite bouquet of whole green cardamom pods, black cardamom, cinnamon sticks, cloves, star anise, mace, and royal cumin seeds.',
        shortDescription: '100% whole whole-spice blend for royal biryanis and rich curries.',
        categoryId: categories[6]._id,
        subcategoryId: subcategories[18]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 250,
        price: 210,
        discountPrice: 185,
        stock: 55,
        lowStockThreshold: 8,
        unit: '100g aroma pack',
        weightKg: 0.15,
        images: [
          'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80',
        ],
        originVillage: 'Purvanchal Spice Mandi',
        originDistrict: 'Varanasi',
        originState: 'Uttar Pradesh',
        status: 'active',
        isOrganic: true,
        rating: 4.9,
        reviewCount: 64,
        tags: ['spices', 'garam-masala', 'shahi', 'cardamom', 'aromatic'],
      },
      {
        title: 'Kashmiri Stemless Mild Red Chilli Powder (Degi Mirch, 200g)',
        sku: 'LH-SP-04',
        slug: 'kashmiri-stemless-red-chilli-powder-200g',
        description: 'Destemmed pure Kashmiri chillies stone-pounded for striking naturally vibrant scarlet red gravy color with very mild, pleasant warmth.',
        shortDescription: 'Natural deep red colorant and gentle warmth for gravies.',
        categoryId: categories[6]._id,
        subcategoryId: subcategories[19]._id,
        sellerId: adminUser._id,
        brand: 'LocalHaat Select',
        mrp: 260,
        price: 220,
        discountPrice: 195,
        stock: 65,
        lowStockThreshold: 10,
        unit: '200g airtight pouch',
        weightKg: 0.25,
        images: [
          'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80',
        ],
        originVillage: 'Purvanchal Spice Mandi',
        originDistrict: 'Varanasi',
        originState: 'Uttar Pradesh',
        status: 'active',
        isOrganic: true,
        rating: 4.8,
        reviewCount: 52,
        tags: ['spices', 'chilli', 'mirch', 'kashmiri', 'color', 'curry'],
      },
    ]);

    console.log('[Seed] Generating Initial Inventory Logs for Store Catalog...');
    for (const p of products) {
      await InventoryLog.create({
        productId: p._id,
        productTitle: p.title,
        sku: p.sku,
        changeType: 'ADD',
        quantityChanged: p.stock,
        previousStock: 0,
        newStock: p.stock,
        reason: 'Initial Admin Catalog Stocking',
        operatorName: adminUser.name,
      });
    }

    console.log('[Seed] Creating Store Discount Coupons...');
    await Coupon.create([
      {
        code: 'WELCOME100',
        description: 'Flat ₹100 OFF on your first grocery and haat order',
        discountType: 'FIXED',
        discountValue: 100,
        minOrderValue: 499,
        maxDiscount: 100,
        usageLimit: 500,
        usedCount: 14,
        customerUsageLimit: 1,
        startDate: new Date(Date.now() - 86400000 * 7),
        expiryDate: new Date(Date.now() + 86400000 * 30),
        isActive: true,
      },
      {
        code: 'MAX500',
        description: '15% OFF up to ₹500 on store staples',
        discountType: 'PERCENTAGE',
        discountValue: 15,
        minOrderValue: 800,
        maxDiscount: 500,
        usageLimit: 1000,
        usedCount: 42,
        customerUsageLimit: 2,
        startDate: new Date(Date.now() - 86400000 * 7),
        expiryDate: new Date(Date.now() + 86400000 * 60),
        isActive: true,
      },
    ]);

    console.log('[Seed] Creating Active Orders & Multi-leg Logistics Test Flows...');

    // Scenario 1: Parcel Ready for Logistics Partner Pickup (Basmati Rice & Mustard Oil)
    // Pickup Code: 841295 | Delivery PIN: 4826 | Handover Code: 572914
    const order1 = await Order.create({
      orderNumber: 'LH-ORD-70192',
      customerId: customerUser._id,
      totalAmount: 849,
      subtotal: 809,
      deliveryFee: 40,
      paymentStatus: 'paid',
      orderStatus: 'confirmed',
      deliveryAddress: customerUser.defaultLocation!,
      deliveryPin: '4826',
      paymentMethod: 'razorpay',
      placedAt: new Date(Date.now() - 3600000 * 4),
    });

    const orderItem1 = await OrderItem.create({
      orderId: order1._id,
      productId: products[0]._id, // Royal Basmati Rice
      sellerId: adminUser._id,
      productTitle: products[0].title,
      productImage: products[0].images[0],
      quantity: 1,
      unitPrice: 599,
      subtotal: 599,
      weightKg: 5.0,
      status: 'packed',
    });

    const orderItem2 = await OrderItem.create({
      orderId: order1._id,
      productId: products[12]._id, // Kachi Ghani Mustard Oil
      sellerId: adminUser._id,
      productTitle: products[12].title,
      productImage: products[12].images[0],
      quantity: 1,
      unitPrice: 210,
      subtotal: 210,
      weightKg: 1.1,
      status: 'packed',
    });

    order1.items = [orderItem1._id, orderItem2._id] as any;

    const parcel1 = await Parcel.create({
      parcelId: 'LH-PKG-904128',
      parcelTrackingNumber: 'LH-TRK-904128',
      senderUserId: customerUser._id,
      senderName: 'LocalHaat Central Warehouse',
      senderMobile: '9999900001',
      pickupLocation: 'Varanasi Central Depot',
      pickupAddress: 'LocalHaat Central Command & Warehouse',
      receiverName: 'Priya Sharma',
      receiverMobile: '9999900005',
      deliveryLocation: 'Ramnagar',
      deliveryAddress: 'House #42, Lane 3, Near Shiv Temple',
      whatIsInside: 'Royal Basmati Rice & Kachi Ghani Mustard Oil',
      parcelCategory: 'Groceries & Staples',
      customerOfferPrice: 180,
      preferredLogisticsType: 'Pickup Van',
      orderId: order1._id,
      orderItems: [orderItem1._id, orderItem2._id],
      senderLocation: adminUser.defaultLocation!,
      destinationLocation: customerUser.defaultLocation!,
      weightKg: 6.1,
      status: 'ready_for_pickup',
      pickupCode: '841295',
      handoverCode: '572914',
      deliveryPin: '4826',
      currentLegIndex: 0,
      totalLegs: 3,
      currentPartnerId: logisticsPartner._id,
      currentAgentId: villageAgent._id,
      currentVehicleId: vehicle._id,
    });

    order1.parcelId = parcel1._id as any;
    await order1.save();

    await ParcelEvent.create([
      {
        parcelId: parcel1._id,
        parcelTrackingNumber: parcel1.parcelTrackingNumber,
        eventType: 'CREATED',
        timestamp: new Date(Date.now() - 3600000 * 4),
        locationName: 'LocalHaat Central Warehouse',
        description: 'Order confirmed and packed by Admin store fulfillment.',
        actorRole: 'Store Admin',
      },
      {
        parcelId: parcel1._id,
        parcelTrackingNumber: parcel1.parcelTrackingNumber,
        eventType: 'READY_FOR_PICKUP',
        timestamp: new Date(Date.now() - 3600000 * 2),
        locationName: 'LocalHaat Central Warehouse',
        description: 'Pickup code 841295 generated for Balwant Singh (Logistics Partner).',
        actorRole: 'System',
      },
    ]);

    await TrackingEvent.create({
      trackingCode: parcel1.parcelTrackingNumber,
      parcelId: parcel1._id,
      status: 'Ready for Pickup',
      locationName: 'Central Haat Warehouse',
      note: 'Awaiting Balwant Singh with pickup code 841295',
    });

    await ShipmentLeg.create([
      {
        parcelId: parcel1._id,
        sequence: 1,
        legType: 'FIRST_MILE_PICKUP',
        originLocation: adminUser.defaultLocation!,
        destinationLocation: {
          addressLine: 'Chunar Transporter Staging Hub',
          villageOrCity: 'Chunar',
          district: 'Mirzapur',
          state: 'Uttar Pradesh',
          pincode: '231304',
        },
        assignedType: 'PARTNER',
        assignedToUserId: partnerUser._id,
        pickupVerificationCode: '841295',
        handoverVerificationCode: '572914',
        status: 'pending',
        distanceKm: 14,
        estimatedEarnings: 65,
      },
      {
        parcelId: parcel1._id,
        sequence: 2,
        legType: 'MID_MILE_HAUL',
        originLocation: {
          addressLine: 'Chunar Transporter Staging Hub',
          villageOrCity: 'Chunar',
          district: 'Mirzapur',
          state: 'Uttar Pradesh',
          pincode: '231304',
        },
        destinationLocation: agentUser.defaultLocation!,
        assignedType: 'PARTNER',
        assignedToUserId: partnerUser._id,
        pickupVerificationCode: '841295',
        handoverVerificationCode: '572914',
        status: 'pending',
        distanceKm: 24,
        estimatedEarnings: 95,
      },
      {
        parcelId: parcel1._id,
        sequence: 3,
        legType: 'LAST_MILE_VILLAGE_DELIVERY',
        originLocation: agentUser.defaultLocation!,
        destinationLocation: customerUser.defaultLocation!,
        assignedType: 'AGENT',
        assignedToUserId: agentUser._id,
        pickupVerificationCode: '572914',
        handoverVerificationCode: '4826',
        status: 'pending',
        distanceKm: 2.5,
        estimatedEarnings: 30,
      },
    ]);

    // Scenario 2: Parcel Arrived at Village Hub, Ready for Delivery to Customer (Terracotta Handi)
    // Customer Delivery PIN: 9173
    const order2 = await Order.create({
      orderNumber: 'LH-ORD-88204',
      customerId: customerUser._id,
      totalAmount: 380,
      subtotal: 340,
      deliveryFee: 40,
      paymentStatus: 'pending', // Cash on Delivery
      orderStatus: 'arrived_at_hub',
      deliveryAddress: customerUser.defaultLocation!,
      deliveryPin: '9173',
      paymentMethod: 'cod',
      placedAt: new Date(Date.now() - 3600000 * 24),
    });

    const orderItem3 = await OrderItem.create({
      orderId: order2._id,
      productId: products[16]._id, // Terracotta Handi
      sellerId: adminUser._id,
      productTitle: products[16].title,
      productImage: products[16].images[0],
      quantity: 1,
      unitPrice: 340,
      subtotal: 340,
      weightKg: 1.6,
      status: 'dispatched',
    });

    order2.items = [orderItem3._id] as any;

    const parcel2 = await Parcel.create({
      parcelId: 'LH-PKG-710492',
      parcelTrackingNumber: 'LH-TRK-710492',
      senderUserId: customerUser._id,
      senderName: 'LocalHaat Central Warehouse',
      senderMobile: '9999900001',
      pickupLocation: 'Varanasi',
      pickupAddress: 'LocalHaat Central Command & Warehouse',
      receiverName: 'Priya Sharma',
      receiverMobile: '9999900005',
      deliveryLocation: 'Ramnagar',
      deliveryAddress: 'House #42, Lane 3, Near Shiv Temple',
      whatIsInside: 'Handcrafted Terracotta Biryani Handi',
      parcelCategory: 'Household & Cookware',
      customerOfferPrice: 150,
      preferredLogisticsType: 'Van / Pickup',
      orderId: order2._id,
      orderItems: [orderItem3._id],
      senderLocation: adminUser.defaultLocation!,
      destinationLocation: customerUser.defaultLocation!,
      weightKg: 1.6,
      status: 'arrived_at_village_hub',
      pickupCode: '319204',
      handoverCode: '662194',
      deliveryPin: '9173',
      currentLegIndex: 2,
      totalLegs: 3,
      currentPartnerId: logisticsPartner._id,
      currentAgentId: villageAgent._id,
      currentVehicleId: vehicle._id,
    });

    order2.parcelId = parcel2._id as any;
    await order2.save();

    await ParcelEvent.create([
      {
        parcelId: parcel2._id,
        parcelTrackingNumber: parcel2.parcelTrackingNumber,
        eventType: 'CREATED',
        timestamp: new Date(Date.now() - 3600000 * 24),
        locationName: 'LocalHaat Central Warehouse',
        description: 'Terracotta handi packed with protective straw cushioning.',
        actorRole: 'Store Admin',
      },
      {
        parcelId: parcel2._id,
        parcelTrackingNumber: parcel2.parcelTrackingNumber,
        eventType: 'PICKED_UP',
        timestamp: new Date(Date.now() - 3600000 * 18),
        locationName: 'LocalHaat Central Warehouse',
        description: 'Picked up by Balwant Singh (Kashi Rural Express).',
        actorRole: 'Logistics Partner',
      },
      {
        parcelId: parcel2._id,
        parcelTrackingNumber: parcel2.parcelTrackingNumber,
        eventType: 'ARRIVED_AT_VILLAGE_HUB',
        timestamp: new Date(Date.now() - 3600000 * 2),
        locationName: 'Ramnagar Panchayat Haat Drop Hub',
        description: 'Received safely at village drop hub by Sudhir Kumar. Ready for customer delivery with PIN 9173.',
        actorRole: 'Village Agent',
      },
    ]);

    await TrackingEvent.create({
      trackingCode: parcel2.parcelTrackingNumber,
      parcelId: parcel2._id,
      status: 'At Village Drop Point Hub',
      locationName: 'Ramnagar Haat Hub',
      note: 'Package ready for delivery/pickup. Present delivery PIN 9173 upon collection.',
    });

    await ShipmentLeg.create([
      {
        parcelId: parcel2._id,
        sequence: 1,
        legType: 'FIRST_MILE_PICKUP',
        originLocation: adminUser.defaultLocation!,
        destinationLocation: {
          addressLine: 'Chunar Transporter Staging Hub',
          villageOrCity: 'Chunar',
          district: 'Mirzapur',
          state: 'Uttar Pradesh',
          pincode: '231304',
        },
        assignedType: 'PARTNER',
        assignedToUserId: partnerUser._id,
        pickupVerificationCode: '319204',
        handoverVerificationCode: '662194',
        status: 'completed',
        distanceKm: 14,
        estimatedEarnings: 65,
        completedAt: new Date(Date.now() - 3600000 * 18),
      },
      {
        parcelId: parcel2._id,
        sequence: 2,
        legType: 'MID_MILE_HAUL',
        originLocation: {
          addressLine: 'Chunar Transporter Staging Hub',
          villageOrCity: 'Chunar',
          district: 'Mirzapur',
          state: 'Uttar Pradesh',
          pincode: '231304',
        },
        destinationLocation: agentUser.defaultLocation!,
        assignedType: 'PARTNER',
        assignedToUserId: partnerUser._id,
        pickupVerificationCode: '319204',
        handoverVerificationCode: '662194',
        status: 'completed',
        distanceKm: 24,
        estimatedEarnings: 95,
        completedAt: new Date(Date.now() - 3600000 * 2),
      },
      {
        parcelId: parcel2._id,
        sequence: 3,
        legType: 'LAST_MILE_VILLAGE_DELIVERY',
        originLocation: agentUser.defaultLocation!,
        destinationLocation: customerUser.defaultLocation!,
        assignedType: 'AGENT',
        assignedToUserId: agentUser._id,
        pickupVerificationCode: '662194',
        handoverVerificationCode: '9173',
        status: 'pending',
        distanceKm: 2.5,
        estimatedEarnings: 30,
      },
    ]);

    // Scenario 3: Parcel in Mid-Mile Transit (Lakadong Turmeric & Wild Forest Honey)
    // Handover Code: 429183
    const order3 = await Order.create({
      orderNumber: 'LH-ORD-91024',
      customerId: customerUser._id,
      totalAmount: 670,
      subtotal: 630,
      deliveryFee: 40,
      paymentStatus: 'paid',
      orderStatus: 'in_transit',
      deliveryAddress: customerUser.defaultLocation!,
      deliveryPin: '3519',
      paymentMethod: 'razorpay',
      placedAt: new Date(Date.now() - 3600000 * 8),
    });

    const orderItem4 = await OrderItem.create({
      orderId: order3._id,
      productId: products[20]._id, // Wild Honey
      sellerId: adminUser._id,
      productTitle: products[20].title,
      productImage: products[20].images[0],
      quantity: 1,
      unitPrice: 390,
      subtotal: 390,
      weightKg: 0.8,
      status: 'dispatched',
    });

    const orderItem5 = await OrderItem.create({
      orderId: order3._id,
      productId: products[24]._id, // Lakadong Turmeric
      sellerId: adminUser._id,
      productTitle: products[24].title,
      productImage: products[24].images[0],
      quantity: 1,
      unitPrice: 240,
      subtotal: 240,
      weightKg: 0.35,
      status: 'dispatched',
    });

    order3.items = [orderItem4._id, orderItem5._id] as any;

    const parcel3 = await Parcel.create({
      parcelId: 'LH-PKG-832109',
      parcelTrackingNumber: 'LH-TRK-832109',
      senderUserId: customerUser._id,
      senderName: 'LocalHaat Central Warehouse',
      senderMobile: '9999900001',
      pickupLocation: 'Varanasi',
      pickupAddress: 'LocalHaat Central Command & Warehouse',
      receiverName: 'Priya Sharma',
      receiverMobile: '9999900005',
      deliveryLocation: 'Ramnagar',
      deliveryAddress: 'House #42, Lane 3, Near Shiv Temple',
      whatIsInside: 'Wild Forest Honey & Lakadong Turmeric Powder',
      parcelCategory: 'Wellness & Spices',
      customerOfferPrice: 200,
      preferredLogisticsType: 'Pickup Van',
      orderId: order3._id,
      orderItems: [orderItem4._id, orderItem5._id],
      senderLocation: adminUser.defaultLocation!,
      destinationLocation: customerUser.defaultLocation!,
      weightKg: 1.15,
      status: 'in_transit',
      pickupCode: '219384',
      handoverCode: '429183',
      deliveryPin: '3519',
      currentLegIndex: 1,
      totalLegs: 3,
      currentPartnerId: logisticsPartner._id,
      currentAgentId: villageAgent._id,
      currentVehicleId: vehicle._id,
    });

    order3.parcelId = parcel3._id as any;
    await order3.save();

    await ParcelEvent.create([
      {
        parcelId: parcel3._id,
        parcelTrackingNumber: parcel3.parcelTrackingNumber,
        eventType: 'CREATED',
        locationName: 'LocalHaat Central Warehouse',
        description: 'Honey & Turmeric packed in bubble padded carton.',
        actorRole: 'Store Admin',
      },
      {
        parcelId: parcel3._id,
        parcelTrackingNumber: parcel3.parcelTrackingNumber,
        eventType: 'PICKED_UP',
        locationName: 'LocalHaat Central Warehouse',
        description: 'Picked up by Balwant Singh (Mahindra Bolero Maxi Truck).',
        actorRole: 'Logistics Partner',
      },
      {
        parcelId: parcel3._id,
        parcelTrackingNumber: parcel3.parcelTrackingNumber,
        eventType: 'IN_TRANSIT',
        locationName: 'GT Road Transporter Corridor',
        description: 'In transit along scheduled corridor towards Ramnagar Village Hub.',
        actorRole: 'Logistics Partner',
      },
    ]);

    await TrackingEvent.create({
      trackingCode: parcel3.parcelTrackingNumber,
      parcelId: parcel3._id,
      status: 'In Transit',
      locationName: 'Chunar-Ramnagar Highway',
      note: 'Driver approaching Ramnagar Village Haat Hub. Handover code 429183.',
    });

    await ShipmentLeg.create([
      {
        parcelId: parcel3._id,
        sequence: 1,
        legType: 'FIRST_MILE_PICKUP',
        originLocation: adminUser.defaultLocation!,
        destinationLocation: {
          addressLine: 'Chunar Hub',
          villageOrCity: 'Chunar',
          district: 'Mirzapur',
          state: 'Uttar Pradesh',
          pincode: '231304',
        },
        assignedType: 'PARTNER',
        assignedToUserId: partnerUser._id,
        pickupVerificationCode: '219384',
        handoverVerificationCode: '429183',
        status: 'completed',
        distanceKm: 14,
        estimatedEarnings: 65,
        completedAt: new Date(Date.now() - 3600000 * 5),
      },
      {
        parcelId: parcel3._id,
        sequence: 2,
        legType: 'MID_MILE_HAUL',
        originLocation: {
          addressLine: 'Chunar Hub',
          villageOrCity: 'Chunar',
          district: 'Mirzapur',
          state: 'Uttar Pradesh',
          pincode: '231304',
        },
        destinationLocation: agentUser.defaultLocation!,
        assignedType: 'PARTNER',
        assignedToUserId: partnerUser._id,
        pickupVerificationCode: '219384',
        handoverVerificationCode: '429183',
        status: 'in_progress',
        distanceKm: 24,
        estimatedEarnings: 95,
        startedAt: new Date(Date.now() - 3600000 * 3),
      },
      {
        parcelId: parcel3._id,
        sequence: 3,
        legType: 'LAST_MILE_VILLAGE_DELIVERY',
        originLocation: agentUser.defaultLocation!,
        destinationLocation: customerUser.defaultLocation!,
        assignedType: 'AGENT',
        assignedToUserId: agentUser._id,
        pickupVerificationCode: '429183',
        handoverVerificationCode: '3519',
        status: 'pending',
        distanceKm: 2.5,
        estimatedEarnings: 30,
      },
    ]);

    // Sample KYC Documents
    await KycDocument.create([
      {
        userId: partnerUser._id,
        documentType: 'DRIVING_LICENSE',
        documentNumber: 'UP65-20180029311',
        documentUrl: 'https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&w=600&q=80',
        verificationStatus: 'VERIFIED',
        verifiedBy: adminUser._id,
        verifiedAt: new Date(),
      },
      {
        userId: sellerUser._id,
        documentType: 'TRADE_LICENSE',
        documentNumber: 'TL-VNS-2024-819',
        documentUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=600&q=80',
        verificationStatus: 'VERIFIED',
      },
    ]);

    // Sample Earnings
    await Earning.create([
      {
        actorType: 'PARTNER',
        actorId: partnerUser._id,
        referenceType: 'SHIPMENT_LEG',
        referenceId: 'LEG-HAUL-091',
        baseAmount: 40,
        bonus: 95,
        deduction: 0,
        netAmount: 135,
        status: 'available',
        remarks: 'Mid-mile haul completed: Sonapur to Ramnagar',
      },
      {
        actorType: 'AGENT',
        actorId: agentUser._id,
        referenceType: 'PARCEL',
        referenceId: parcel2.parcelTrackingNumber,
        baseAmount: 30,
        bonus: 0,
        deduction: 0,
        netAmount: 30,
        status: 'available',
        remarks: 'Hub intake and package sorting completed',
      },
    ]);

    // Sample Notifications
    await Notification.create([
      {
        userId: customerUser._id,
        title: 'Package Arrived at Local Hub! 📍',
        message: 'Your parcel LH-TRK-710492 has arrived at Ramnagar Haat Hub. Your Delivery PIN is 9173.',
        type: 'IN_APP',
      },
      {
        userId: partnerUser._id,
        title: 'New Pickup Leg Assigned 🚛',
        message: 'Parcel LH-TRK-904128 is ready for pickup in Sonapur. Pickup Code: 841295',
        type: 'IN_APP',
      },
      {
        userId: agentUser._id,
        title: 'Incoming Transit Expected 📦',
        message: 'Kashi Rural Express is arriving with 1 package scheduled for Ramnagar.',
        type: 'IN_APP',
      },
    ]);

    console.log('[Seed] Database successfully seeded with authentic Admin Company Store Catalog!');
    console.log('----------------------------------------------------');
    console.log('COMPANY STORE CATALOG STATS:');
    console.log(`- Categories:     ${categories.length} (Rice, Daal, Aata, FMCG, Household, Personal Care, Spices)`);
    console.log(`- Subcategories:  ${subcategories.length}`);
    console.log(`- Products:       ${products.length} (All owned by Company Admin)`);
    console.log('----------------------------------------------------');
    console.log('DEMO ACCOUNTS READY (Use any phone + OTP "123456"):');
    console.log('1. Admin (Store Owner): Phone: 9999900001 | Email: gokul@localhaat.in | Pass: gokul@1996 (Gokul)');
    console.log('2. Business / Supplier: Phone: 9999900002 (Rameshwar Mahato)');
    console.log('3. Logistics Partner:   Phone: 9999900003 (Balwant Singh)');
    console.log('4. Village Agent:       Phone: 9999900004 (Sudhir Kumar)');
    console.log('5. Customer:            Phone: 9999900005 (Priya Sharma)');
    console.log('----------------------------------------------------');
    console.log('ACTIVE TEST CODES:');
    console.log('Parcel 1 (LH-TRK-904128) [Ready for Pickup] -> Pickup Code: 841295');
    console.log('Parcel 2 (LH-TRK-710492) [At Village Hub]   -> Delivery PIN: 9173 (Handover Code: 662194)');
    console.log('Parcel 3 (LH-TRK-832109) [In Transit]       -> Handover Code: 429183');
    console.log('----------------------------------------------------');

    const { seedRichAgents } = await import('./seedAgentsData.js');
    await seedRichAgents();


    if (shouldDisconnect) {
      await disconnectDB();
    }
  } catch (error) {
    console.error('[Seed Error]:', error);
    if (shouldDisconnect) {
      await disconnectDB();
      process.exit(1);
    }
    throw error;
  }
};

// If run directly
if (process.argv[1] && process.argv[1].replace(/\\/g, '/').includes('seedData')) {
  seedDatabase();
}
